#名字字典
---
#阐截斗法相关配置
key: 唯一
#姓氏列表：百家姓+现存的81个复姓
surName: "赵,钱,孙,李,周,吴,郑,王,冯,陈,楮,卫,蒋,沈,韩,杨,朱,秦,尤,许,何,吕,施,张,孔,曹,严,华,金
,魏,陶,姜,戚,谢,邹,喻,柏,水,窦,章,云,苏,潘,葛,奚,范,彭,郎,鲁,韦,昌,马,苗,凤,花,方,俞,任,袁,柳,酆
,鲍,史,唐,费,廉,岑,薛,雷,贺,倪,汤,滕,殷,罗,毕,郝,邬,安,常,乐,于,时,傅,皮,卞,齐,康,伍,余,元,卜,顾
,孟,平,黄,和,穆,萧,尹,姚,邵,湛,汪,祁,毛,禹,狄,米,贝,明,臧,计,伏,成,戴,谈,宋,茅,庞,熊,纪,舒,屈,项
,祝,董,梁,杜,阮,蓝,闽,席,季,麻,强,贾,路,娄,危,江,童,颜,郭,梅,盛,林,刁,锺,徐,丘,骆,高,夏,蔡,田,樊
,胡,凌,霍,虞,万,支,柯,昝,管,卢,莫,经,房,裘,缪,干,解,应,宗,丁,宣,贲,邓,郁,单,杭,洪,包,诸,左,石,崔
,吉,钮,龚,程,嵇,邢,滑,裴,陆,荣,翁,荀,羊,於,惠,甄,麹,家,封,芮,羿,储,靳,汲,邴,糜,松,井,段,富,巫,乌
,焦,巴,弓,牧,隗,山,谷,车,侯,宓,蓬,全,郗,班,仰,秋,仲,伊,宫,宁,仇,栾,暴,甘,斜,厉,戎,祖,武,符,刘,景
,詹,束,龙,叶,幸,司,韶,郜,黎,蓟,薄,印,宿,白,怀,蒲,邰,从,鄂,索,咸,籍,赖,卓,蔺,屠,蒙,池,乔,阴,郁,胥
,能,苍,双,闻,莘,党,翟,谭,贡,劳,逄,姬,申,扶,堵,冉,宰,郦,雍,郤,璩,桑,桂,濮,牛,寿,通,边,扈,燕,冀,郏
,浦,尚,农,温,别,庄,晏,柴,瞿,阎,充,慕,连,茹,习,宦,艾,鱼,容,向,古,易,慎,戈,廖,庾,终,暨,居,衡,步,都
,耿,满,弘,匡,国,文,寇,广,禄,阙,东,欧,殳,沃,利,蔚,越,夔,隆,师,巩,厍,聂,晁,勾,敖,融,冷,訾,辛,阚,那
,简,饶,空,曾,毋,沙,乜,养,鞠,须,丰,巢,关,蒯,相,查,后,荆,红,游,竺,权,逑,盖,益,桓,公,晋,楚,阎,法,汝
,鄢,涂,钦,岳,帅,缑,亢,况,后,有,琴,商,牟,佘,佴,伯,赏,墨,哈,谯,笪,年,爱,阳,佟,欧阳,太史,端木,上官
,司马,东方,独孤,南宫,万俟,闻人,夏侯,诸葛,尉迟,公羊,赫连,澹台,皇甫,宗政,濮阳,公冶,太叔,申屠,公孙
,慕容,仲孙,钟离,长孙,宇文,司徒,鲜于,司空,闾丘,子车,亓官,司寇,巫马,公西,颛孙,壤驷,公良,漆雕
,乐正,宰父,谷梁,拓跋,夹谷,轩辕,令狐,段干,百里,呼延,东郭,南门,羊舌,微生,公户,公玉,公仪,梁丘
,公仲,公上,公门,公山,公坚,左丘,公伯,西门,公祖,第五,公乘,贯丘,公皙,南荣,东里,东宫,仲长,子书
,子桑,即墨,达奚,褚师,吴铭"

word: "筱,若,湘,玥,媱,汐,瑄,羽,霏,影,沫,燕,泠,梓,言,
斓,璃,落,矞,琅,湛,露,浅,采,然,流,梦,溪,墨,染,冰,绡,舞,
野,凝,纱,菡,弈,宸,烨,岚,漠,庭,城,途,伯,弘,枭,律,哲,凌,
沙,辞,汉,恺,斯,烟,暘,寒,离,尘,崖,伞,谪,泽,扬,赫,穆,独,
绝,轩,舒,影,荔,枝,丽,秀,娟,英,华,慧,巧,美,静,淑,惠,珠,
莹,雪,琳,晗,瑶,勤,珍,贞,莉,兰,凤,洁,琳,素,云,莲,真,环,
月,媛,艳,瑞,凡,佳,嘉,叶,璧,璐,娅,琦,晶,妍,茜,秋,珊,莎,
锦,婕,馨,瑗,琰,融,艺,咏,卿,聪,澜,纯,毓,悦,昭,冰,爽,琬,
茗,羽,希,宁,欣,飘,育,涵,琴,晴,丽,美,瑶,梦,茜,倩,希,夕,
月,悦,乐,彤,影,珍,依,沫,玉,灵,瑶,嫣,倩,妍,萱,漩,娅,媛,
怡,佩,淇,雨,娜,莹,娟,文,芳,莉,雅,诗,乐,佳,涵,珊,莎,锦,
黛,青,倩,姣,婉,娴,瑾,颖,雯,婕,馨,洁,琳,薇,菁,梦,岚,苑,
荣,爱,政,谦,康,星,光,天,达,安,清,飞,彬,富,顺,信,子,杰,涛,
贵,福,生,龙,元,全,国,胜,学,祥,才,发,武,新,亨,奇,滕,炅,炜,
伟,刚,勇,毅,俊,峰,强,军,平,保,东,文,辉,力,固,之,段,殿,泰,
利,清,飞,彬,富,顺,信,子,杰,涛,昌,成,康,星,翰,晸,利,武,新,
若,鸣,朋,斌,梁,栋,维,启,克,伦,翔,旭,鹏,泽,朗,伯,昮,晋,晟,
诚,先,敬,震,振,壮,会,思,群,豪,心,邦,承,乐,宏,言,旲,旻,昊,
光,天,达,安,岩,中,茂,进,林,有,坚,和,彪,博,泰,盛,振,挺,掣,
明,永,健,世,广,志,义,兴,良,海,山,仁,波,宁,行,时,志,忠,思,
绍,功,松,善,厚,庆,磊,民,友,裕,河,哲,江,超,炎,德,彰,征,律,
晨,辰,士,以,建,家,致,煜,煊,炎,波,宁,贵,福,生,龙,元,全,国,
胜,学,祥,才,发,昌,成,樱,飒,枫,尘,辰,晨,恒,痕,
若晴,倾璃,乔熙,篱落,孤烟,残霜,森凉,珞璎,柒祭,染栀,柠栀,瑾淋,汐屿,玖怜,未易,
吟鹭,斐颜,析芷,南枭,北城,冬彦,晰慕,昭锌,若初,陌白,凉白,岚榕,往昔,辛葶,若离,厌离,蝶怜,悯溯,白初,尘世,
沉湘,栩瑾,鲸落,弦如,熄颜,墨语,陌噬,挽心,皖歌,琼恨,逸轩,易韵,飒言,枫亭,凉沁,惜逝,九黎,寺念,念白,捻漓,
亦寒,顾兮,玖潮,若邪,淋璃,沐瑾,竹惟,仙黎,怜心,汐雨,卿陌,樱梦,萱月,凌若,愿璃,夙浅,白韵,墨郁,竹凉,暮宸,
离念,初瑾,楚婉,落清,默言,琉语,幽染,决澜,临城,浮歌,桃夭,灼华,秋舞,如溪,绯衣,仟御,殇绝,冶媚,妖璇,晗晴,
潇泠,流凝,思鸾,矜慕,笙沫,绫玥,涟珊
"

...