#CfgSuper16

#betBegin:竞猜开始时间
#betEnd:竞猜结束时间
#showBegin: 展示开始时间
#showEnd: 展示结束时间
#quizs: 竞猜内容
#group：分组
#competeCountries:参与的国家
#winCountry:胜利的国家
#needTreasure:消耗道具的Id
#num:消耗道具的数量
key: 唯一

betBegin: 2022-11-20 00:00:00
betEnd: 2022-11-23 23:59:59
showBegin: 2022-11-24 00:00:00
showEnd: 2022-12-20 00:00:00
quizs:
  - {group: A,competeCountries:[1,2,3,4],winCountry:[3,4],needTreasure: 50430,num: 3}
  - {group: B,competeCountries:[5,6,7,8],winCountry:[5,7],needTreasure: 50430,num: 3}
  - {group: C,competeCountries:[9,10,11,12],winCountry:[9,12],needTreasure: 50430,num: 3}
  - {group: D,competeCountries:[13,14,15,16],winCountry:[13,16],needTreasure: 50430,num: 3}
  - {group: E,competeCountries:[17,18,19,20],winCountry:[17,19],needTreasure: 50430,num: 3}
  - {group: F,competeCountries:[21,22,23,24],winCountry:[23,24],needTreasure: 50430,num: 3}
  - {group: G,competeCountries:[25,26,27,28],winCountry:[25,27],needTreasure: 50430,num: 3}
  - {group: H,competeCountries:[29,30,31,32],winCountry:[29,32],needTreasure: 50430,num: 3}

quizAwards:

  - {successTimes: 0,awards: [{awardId: 50431,item: 60,num: 50}]}
  - {successTimes: 1,awards: [{awardId: 50431,item: 60,num: 100}]}
  - {successTimes: 2,awards: [{awardId: 50431,item: 60,num: 220}]}
  - {successTimes: 3,awards: [{awardId: 50431,item: 60,num: 360}]}
  - {successTimes: 4,awards: [{awardId: 50431,item: 60,num: 520}]}
  - {successTimes: 5,awards: [{awardId: 50431,item: 60,num: 700}]}
  - {successTimes: 6,awards: [{awardId: 50431,item: 60,num: 900}]}
  - {successTimes: 7,awards: [{awardId: 50431,item: 60,num: 1120}]}
  - {successTimes: 8,awards: [{awardId: 50431,item: 60,num: 1360}]}
  - {successTimes: 9,awards: [{awardId: 50431,item: 60,num: 1620}]}
  - {successTimes: 10,awards: [{awardId: 50431,item: 60,num: 1900}]}
  - {successTimes: 11,awards: [{awardId: 50431,item: 60,num: 2200}]}
  - {successTimes: 12,awards: [{awardId: 50431,item: 60,num: 2520}]}
  - {successTimes: 13,awards: [{awardId: 50431,item: 60,num: 2860}]}
  - {successTimes: 14,awards: [{awardId: 50431,item: 60,num: 3220}]}
  - {successTimes: 15,awards: [{awardId: 50431,item: 60,num: 3600}]}
  - {successTimes: 16,awards: [{awardId: 50431,item: 60,num: 4000}]}