#轮回时间
#CfgTransmigration
key: 唯一
# 开放的区服组
sgIds: [16,20]
# 首轮开始时间
firstBeginDate: 2021-09-29 08:00:00
# 首轮结束时间
firstEndDate: 2021-10-10 22:00:00
#开始时分秒
beginHms: 08:00:00
#结束时分秒
endHms: 22:00:00
#空挡天数（结束后第二天）
gapDays: 1
#持续天数
duration: 21
#高光记录数
highLightNum: 50
#高光最小分数要求
highLightMinScore: 80
#初始主城属性
firstMainCityDefenderTypes: [30,40,20,50,10]
#城池特性
cityEffects: [131003,131004,131008,131007]
#城池第一名加分
extraScoreForCityNo1: 10
#精英野怪额外概率10%
eltiteYgExtraProb: 1000
# 解锁需要的城池数
unlockCityNum: 65
#显示图标需要的城池数
showIconCityNum: 45
#守将规则
defenders:
  - {cityLv: 1,type: 0,defenderLv: 160,defenderRunes: [1,2],runeNum: 1,cardHvInterval: [10,10],cardLvInterval: [25,35],cards: [{stars: [5],num: 4},{stars: [4],num: 4},{stars: [1,2,3,4,5],num: 7}]}
  - {cityLv: 2,type: 0,defenderLv: 160,defenderRunes: [1,2],runeNum: 1,cardHvInterval: [10,10],cardLvInterval: [25,35],cards: [{stars: [5],num: 4},{stars: [4],num: 4},{stars: [1,2,3,4,5],num: 7}]}
  - {cityLv: 3,type: 0,defenderLv: 160,defenderRunes: [1,2,3],runeNum: 1,cardHvInterval: [10,10],cardLvInterval: [30,40],cards: [{stars: [5],num: 5},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
  - {cityLv: 4,type: 0,defenderLv: 160,defenderRunes: [1,3],runeNum: 1,cardHvInterval: [10,10],cardLvInterval: [30,40],cards: [{stars: [5],num: 5},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
  - {cityLv: 5,type: 10,defenderLv: 160,defenderRunes: [1,3],runeNum: 2,cardHvInterval: [10,10],cardLvInterval: [40,40],cards: [{cardIds: [126]},{stars: [5],num: 4},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
  - {cityLv: 5,type: 20,defenderLv: 160,defenderRunes: [1,3],runeNum: 2,cardHvInterval: [10,10],cardLvInterval: [40,40],cards: [{cardIds: [226]},{stars: [5],num: 4},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
  - {cityLv: 5,type: 30,defenderLv: 160,defenderRunes: [1,3],runeNum: 2,cardHvInterval: [10,10],cardLvInterval: [40,40],cards: [{cardIds: [10325]},{stars: [5],num: 4},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
  - {cityLv: 5,type: 40,defenderLv: 160,defenderRunes: [1,3],runeNum: 2,cardHvInterval: [10,10],cardLvInterval: [40,40],cards: [{cardIds: [425]},{stars: [5],num: 4},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
  - {cityLv: 5,type: 50,defenderLv: 160,defenderRunes: [1,3],runeNum: 2,cardHvInterval: [10,10],cardLvInterval: [40,40],cards: [{cardIds: [525]},{stars: [5],num: 4},{stars: [4],num: 5},{stars: [1,2,3,4,5],num: 10}]}
#区域划分
areaDevision:
  10: [西歧,蜀丘,陈塘关,凉州,昆仑,丰镐,首阳,绝龙岭,西亳,太华,三津里,即韦,临羌,泾谷,羌西,河西,悬圃]
  20: [东鲁,徐州,白鹿岛,兖州,蓬莱,孟津,九龙岛,云间,棋盘山,有穷,人方,汜叶,斟寻,斟灌,曹邑,金鳌岛,芒池]
  30: [曹州,冀州,青州,冥海,崇城,北海,幽州,不死山,涂山,朔方]
  40: [南都,凤山,扬州,荆州,蛮阈,苗疆,火龙岛,苍梧,常羊,河阴,壑市,流波山,巫沼,夷越,水峒,河曲,沙洲]
  50: [朝歌,佳梦关,雍州,豫州,游魂关,青龙关,三山关,渑池,东莱,轩辕台,牧野,有虞,卫畿,鸣条,界牌关,汜水,穿云关,营州,涿鹿,桓山,并州,卫服,河上,马邑]
#轮回buff
transmigrationBuff:
  - {min: 1,max: 5,add: 0.01}
  - {min: 6,max: 10,add: 0.02}
  - {min: 11,max: 15,add: 0.03}
  - {min: 16,max: 20,add: 0.04}
  - {min: 21,max: 25,add: 0.05}
  - {min: 26,max: 30,add: 0.06}
  - {min: 31,max: 35,add: 0.07}
  - {min: 36,max: 40,add: 0.08}
  - {min: 41,max: 45,add: 0.09}
  - {min: 46,max: 50,add: 0.10}
  - {min: 51,max: 55,add: 0.11}
  - {min: 56,max: 60,add: 0.12}
  - {min: 61,max: 65,add: 0.13}
  - {min: 66,max: 70,add: 0.14}
  - {min: 71,max: 75,add: 0.15}
  - {min: 76,max: 80,add: 0.16}
  - {min: 81,max: 82,add: 0.19}
  - {min: 83,max: 84,add: 0.22}
  - {min: 85,max: 85,add: 0.25}
#评分目标奖励
targets:
  - {id: 1,needScore: 1800,awards: [{item: 60,awardId: 11010,num: 10}]}
  - {id: 2,needScore: 2300,awards: [{item: 60,awardId: 50198,num: 1000}]}
  - {id: 3,needScore: 2800,awards: [{item: 20,num: 1000000},{item: 60,awardId: 10020,num: 40}]}
  - {id: 4,needScore: 3300,awards: [{item: 60,awardId: 11010,num: 20}]}
  - {id: 5,needScore: 3800,awards: [{item: 60,awardId: 50198,num: 3000}]}
  - {id: 6,needScore: 4300,awards: [{item: 60,awardId: 11060,num: 1}]}
  - {id: 7,needScore: 4800,awards: [{item: 60,awardId: 50130,num: 2},{item: 60,awardId: 50128,num: 20}]}
  - {id: 8,needScore: 5300,awards: [{item: 60,awardId: 50198,num: 5000}]}
  - {id: 9,needScore: 5800,awards: [{item: 60,awardId: 10180,num: 50}]}
  - {id: 10,needScore: 6300,awards: [{item: 60,awardId: 11400,num: 1}]}
  - {id: 11,needScore: 6800,awards: [{item: 60,awardId: 50198,num: 8000}]}
  - {id: 12,needScore: 7300,awards: [{item: 60,awardId: 50131,num: 2},{item: 60,awardId: 50129,num: 2}]}
  - {id: 13,needScore: 8000,awards: [{item: 60,awardId: 50010,num: 1}]}
#排行奖励(弃用)
rankerAwards:
  - {minRank: 1,maxRank: 1,awards: [{item: 60,awardId: 50011,num: 2},{item: 60,awardId: 11010,num: 50},{item: 60,awardId: 10020,num: 200},{item: 20,num: 5000000}]}
  - {minRank: 2,maxRank: 2,awards: [{item: 60,awardId: 50011,num: 1},{item: 60,awardId: 11010,num: 40},{item: 60,awardId: 10020,num: 150},{item: 20,num: 3000000}]}
  - {minRank: 3,maxRank: 3,awards: [{item: 60,awardId: 50011,num: 1},{item: 60,awardId: 11010,num: 30},{item: 60,awardId: 10020,num: 130},{item: 20,num: 2000000}]}
  - {minRank: 4,maxRank: 6,awards: [{item: 60,awardId: 50011,num: 1},{item: 60,awardId: 11010,num: 25},{item: 60,awardId: 10020,num: 110},{item: 20,num: 1500000}]}
  - {minRank: 7,maxRank: 10,awards: [{item: 60,awardId: 50011,num: 1},{item: 60,awardId: 11010,num: 20},{item: 60,awardId: 10020,num: 90},{item: 20,num: 1300000}]}
  - {minRank: 11,maxRank: 20,awards: [{item: 60,awardId: 50012,num: 100},{item: 60,awardId: 11010,num: 15},{item: 60,awardId: 10020,num: 70},{item: 20,num: 1100000}]}
  - {minRank: 21,maxRank: 50,awards: [{item: 60,awardId: 50012,num: 80},{item: 60,awardId: 11010,num: 12},{item: 60,awardId: 10020,num: 50},{item: 20,num: 900000}]}
  - {minRank: 51,maxRank: 100,awards: [{item: 60,awardId: 50012,num: 60},{item: 60,awardId: 11010,num: 10},{item: 60,awardId: 10020,num: 30},{item: 20,num: 700000}]}
  - {minRank: 101,maxRank: 200,awards: [{item: 60,awardId: 50012,num: 40},{item: 60,awardId: 11010,num: 8},{item: 60,awardId: 10020,num: 20},{item: 20,num: 500000}]}
  - {minRank: 201,maxRank: 9999999,awards: [{item: 60,awardId: 50012,num: 20},{item: 60,awardId: 11010,num: 6},{item: 60,awardId: 10020,num: 10},{item: 20,num: 300000}]}

