#碧游宫技能配置
#CfgBYPalaceSkillEntity
#type属性  chapter篇  skills技能集
--- {id: 101,type: 金,chapter: 1,skills: [金-避雷,金-心止,金-自在,一星金仙决]}
--- {id: 102,type: 金,chapter: 2,skills: [金-真金,金-定风,金-返照,金-自愈,金-无相,金-得道,金-疾驰,金-火球,金-暴起,金-法盾,金-克敌,二星金仙决]}
--- {id: 103,type: 金,chapter: 3,skills: [金-神剑,金-奇袭,金-突袭,金-飞行,金-穿刺,金-修仙,金-回光,金-死斗,金-嗜血,金-护卫,金-宝鉴,金-法身,三星金仙决]}
--- {id: 104,type: 金,chapter: 4,skills: [金-升仙,金-枷锁,金-死士,金-暴击,金-闪电,金-偷营,金-怒意,四星金仙决]}
--- {id: 105,type: 金,chapter: 5,skills: [金-强水,金-生水,金-威风,金-主帅,金-联攻,金-龙息,金-力盾,金-火枪,五星金仙决]}

--- {id: 201,type: 木,chapter: 1,skills: [木-避雷,木-心止,木-自在,一星木仙决]}
--- {id: 202,type: 木,chapter: 2,skills: [木-真金,木-定风,木-返照,木-自愈,木-飞狙,木-无相,木-修仙,木-疾驰,木-护卫,木-暴起,木-法盾,木-克敌,二星木仙决]}
--- {id: 203,type: 木,chapter: 3,skills: [木-祛毒,木-神疗,木-飞行,木-拦截,木-穿刺,木-治愈,木-得道,木-回光,木-流毒,木-入痘,木-挑拨,木-法身,三星木仙决]}
--- {id: 204,type: 木,chapter: 4,skills: [木-灭魄,木-升仙,木-枷锁,木-死士,木-灵动,木-力盾,木-坚毅,四星木仙决]}
--- {id: 205,type: 木,chapter: 5,skills: [木-强火,木-生火,木-回魂,木-复活,木-联攻,木-刚毅,木-长生,木-双狙,木-暗蛊,五星木仙决]}

--- {id: 301,type: 水,chapter: 1,skills: [水-避雷,水-心止,水-自在,一星水仙决]}
--- {id: 302,type: 水,chapter: 2,skills: [水-真金,水-定风,水-返照,水-自愈,水-无相,水-得道,水-疾驰,水-暴起,水-宝鉴,水-法盾,水-克敌,二星水仙决]}
--- {id: 303,type: 水,chapter: 3,skills: [水-神疗,水-飞行,水-治愈,水-吸血,水-闪电,水-噬魂,水-修仙,水-回光,水-流毒,水-入痘,水-护卫,水-法身,三星水仙决]}
--- {id: 304,type: 水,chapter: 4,skills: [水-升仙,水-拦截,水-灵动,水-怨灵,水-死咒,水-巫医,水-魅惑,水-挑拨,四星水仙决]}
--- {id: 305,type: 水,chapter: 5,skills: [水-强木,水-生木,水-回魂,水-妖术,水-联攻,水-销魂,水-兴法,水-暗蛊,五星水仙决]}

--- {id: 401,type: 火,chapter: 1,skills: [火-避雷,火-心止,火-自在,一星火仙决]}
--- {id: 402,type: 火,chapter: 2,skills: [火-真金,火-定风,火-返照,火-自愈,火-无相,火-噬魂,火-修仙,火-疾驰,火-火球,火-暴起,火-法盾,火-克敌,二星火仙决]}
--- {id: 403,type: 火,chapter: 3,skills: [火-祛毒,火-奇袭,火-飞行,火-穿刺,火-吸血,火-闪电,火-业火,火-得道,火-死士,火-流毒,火-护卫,火-法身,三星火仙决]}
--- {id: 404,type: 火,chapter: 4,skills: [火-业火-圣火,火-魅惑,火-枷锁,火-怨灵,火-瘟君,火-偷营,火-炙焰,火-怒意,火-火枪,四星火仙决]}
--- {id: 405,type: 火,chapter: 5,skills: [火-强土,火-生土,火-妖术,火-混元,火-联攻,火-死咒,火-巫医,火-兴法,火-炙焰-烈焰,五星火仙决]}

--- {id: 501,type: 土,chapter: 1,skills: [土-避雷,土-心止,土-自在,一星土仙决]}
--- {id: 502,type: 土,chapter: 2,skills: [土-真金,土-定风,土-返照,土-自愈,土-穿刺,土-无相,土-疾驰,土-暴起,土-宝鉴,土-法盾,土-克敌,二星土仙决]}
--- {id: 503,type: 土,chapter: 3,skills: [土-飞狙,土-突袭,土-飞行,土-噬魂,土-修仙,土-得道,土-死士,土-嗜血,土-入痘,土-护卫,土-法身,三星土仙决]}
--- {id: 504,type: 土,chapter: 4,skills: [土-灭魄,土-闪电,土-死斗,土-暴击,土-瘟君,土-飞狙-双狙,土-坚毅,四星土仙决]}
--- {id: 505,type: 土,chapter: 5,skills: [土-强金,土-生金,土-威风,土-联攻,土-刚毅,土-龙息,土-钻地,五星土仙决]}

--- {id: 698,type: 秘传,chapter: 98,skills: [全-超度,全-封神,全-招财,全-封咒,全-蛊惑,全-禁术,全-长生,全-吸星,全-枷锁-连锁,全-钻地-地劫,全-鼓舞,全-妖术-绝杀,全-闪电-雷电,全-怨灵-咒怨,全-震慑,全-芒刺-战刺,全-回光-反射,全-挑拨-反间,全-激励,全-袍泽,全-悲愤,全-食尸,全-灵守,全-镜像,全-蚀月]}
--- {id: 699,type: 秘传,chapter: 99,skills: [全-超度,全-封神,全-招财,全-封咒,全-蛊惑,全-禁术,全-长生,全-吸星,全-枷锁-连锁,全-钻地-地劫,全-鼓舞,全-妖术-绝杀,全-闪电-雷电,全-怨灵-咒怨,全-震慑,全-芒刺-战刺,全-回光-反射,全-挑拨-反间,全-激励,全-袍泽,全-悲愤,全-食尸,全-灵守,全-镜像,全-蚀月]}