#奖券
#CfgHolidayLotteryAwards
#type=10
--- {id: 0,type: 10,prop: 0,order: 1, awards: [{item: 40,awardId: 251,num: 1}]}
--- {id: 1010,type: 10,prop: 50,order: 2,awards: [{item: 60,awardId: 11060,num: 1}]}
--- {id: 1020,type: 10,prop: 100,order: 6,awards: [{item: 60,awardId: 10170,num: 1}]}
--- {id: 1030,type: 10,prop: 25,order: 3,awards: [{item: 60,awardId: 20150,num: 1}]}
--- {id: 1040,type: 10,prop: 25,order: 4,awards: [{item: 60,awardId: 20250,num: 1}]}
--- {id: 1050,type: 10,prop: 150,order: 5,awards: [{item: 60,awardId: 850,num: 1}]}
--- {id: 1070,type: 10,prop: 100,order: 21,awards: [{item: 60,awardId: 20140,num: 1}]}
--- {id: 1080,type: 10,prop: 100,order: 22,awards: [{item: 60,awardId: 20240,num: 1}]}
--- {id: 1090,type: 10,prop: 200,order: 13,awards: [{item: 60,awardId: 10,num: 1}]}
--- {id: 1100,type: 10,prop: 200,order: 14,awards: [{item: 60,awardId: 20,num: 1}]}
--- {id: 1110,type: 10,prop: 200,order: 8,awards: [{item: 60,awardId: 840,num: 1}]}
--- {id: 1120,type: 10,prop: 200,order: 15,awards: [{item: 60,awardId: 520,num: 1}]}
--- {id: 1130,type: 10,prop: 200,order: 23,awards: [{item: 60,awardId: 20130,num: 1}]}
--- {id: 1140,type: 10,prop: 200,order: 24,awards: [{item: 60,awardId: 20230,num: 1}]}
--- {id: 1150,type: 10,prop: 300,order: 9,awards: [{item: 60,awardId: 10010,num: 1}]}
--- {id: 1160,type: 10,prop: 400,order: 25,awards: [{item: 60,awardId: 20120,num: 1}]}
--- {id: 1170,type: 10,prop: 400,order: 26,awards: [{item: 60,awardId: 20220,num: 1}]}
--- {id: 1180,type: 10,prop: 500,order: 7,awards: [{item: 60,awardId: 830,num: 3}]}
--- {id: 1190,type: 10,prop: 500,order: 10,awards: [{item: 60,awardId: 210,num: 1}]}
--- {id: 1200,type: 10,prop: 500,order: 11,awards: [{item: 60,awardId: 260,num: 1}]}
--- {id: 1210,type: 10,prop: 500,order: 12,awards: [{item: 60,awardId: 60,num: 1}]}
--- {id: 1220,type: 10,prop: 700,order: 16,awards: [{item: 60,awardId: 10030,num: 2}]}
--- {id: 1230,type: 10,prop: 700,order: 17,awards: [{item: 60,awardId: 10180,num: 2}]}
--- {id: 1240,type: 10,prop: 700,order: 18,awards: [{item: 60,awardId: 11090,num: 2}]}
--- {id: 1250,type: 10,prop: 700,order: 19,awards: [{item: 60,awardId: 11010,num: 3}]}
--- {id: 1260,type: 10,prop: 700,order: 20,awards: [{item: 60,awardId: 10110,num: 1}]}
--- {id: 1270,type: 10,prop: 800,order: 27,awards: [{item: 60,awardId: 10180,num: 1}]}
--- {id: 1280,type: 10,prop: 850,order: 28,awards: [{item: 60,awardId: 11010,num: 2}]}
#type=20
--- {id: 2010,type: 20,level: 10,order: 1,awards: [{item: 60,awardId: 11410,num: 1},{item: 10,num: 688},{item: 60,awardId: 11300,num: 1}]}
--- {id: 2020,type: 20,level: 20,order: 2,awards: [{item: 60,awardId: 10110,num: 9},{item: 10,num: 388}]}
--- {id: 2030,type: 20,level: 30,order: 3,awards: [{item: 60,awardId: 10180,num: 9},{item: 10,num: 288}]}
--- {id: 2040,type: 20,level: 40,order: 4,awards: [{item: 60,awardId: 11010,num: 5},{item: 10,num: 188}]}
--- {id: 2050,type: 20,level: 50,order: 5,awards: [{item: 60,awardId: 11090,num: 2},{item: 10,num: 158}]}
--- {id: 2060,type: 20,level: 60,order: 6,awards: [{item: 60,awardId: 10180,num: 1},{item: 10,num: 88}]}
--- {id: 2070,type: 20,level: 70,order: 7,awards: [{item: 60,awardId: 10020,num: 3},{item: 10,num: 58}]}
#type=30 五气朝元
--- {id: 3010,type: 30,level: 0, order: 1,num: 1,awards: [{item: 40,awardId: 350,num: 1}]}
--- {id: 3020,type: 30,level: 1, order: 2,num: 1,awards: [{item: 40,awardId: 548,num: 1}]}
--- {id: 3030,type: 30,level: 2, order: 3,num: 1,awards: [{item: 60,awardId: 11400,num: 1}]}
--- {id: 3040,type: 30,level: 3, order: 4,num: 1,awards: [{item: 60,awardId: 11060,num: 1}]}
--- {id: 3050,type: 30,level: 4, order: 5,num: 1,awards: [{item: 60,awardId: 11410,num: 1}]}
--- {id: 3060,type: 30,level: 5, order: 6,num: 2,awards: [{item: 60,awardId: 10180,num: 3}]}
--- {id: 3070,type: 30,level: 7, order: 7,num: 5,awards: [{item: 60,awardId: 10180,num: 2}]}
--- {id: 3080,type: 30,level: 12, order: 8,num: 6,awards: [{item: 60,awardId: 10180,num: 1}]}
--- {id: 3090,type: 30,level: 18, order: 9,num: 15,awards: [{item: 60,awardId: 50207,num: 1}]}
--- {id: 3100,type: 30,level: 33, order: 10,num: 10,awards: [{item: 60,awardId: 50198,num: 60}]}
--- {id: 3110,type: 30,level: 43, order: 11,num: 2,awards: [{item: 60,awardId: 10020,num: 30}]}
--- {id: 3120,type: 30,level: 45, order: 12,num: 3,awards: [{item: 60,awardId: 10020,num: 20}]}
--- {id: 3130,type: 30,level: 48, order: 13,num: 6,awards: [{item: 60,awardId: 10020,num: 10}]}
--- {id: 3140,type: 30,level: 54, order: 14,num: 9,awards: [{item: 60,awardId: 10020,num: 8}]}
--- {id: 3150,type: 30,level: 63, order: 15,num: 2,awards: [{item: 10,num: 120}]}
--- {id: 3160,type: 30,level: 65, order: 16,num: 3,awards: [{item: 10,num: 100}]}
--- {id: 3170,type: 30,level: 68, order: 17,num: 5,awards: [{item: 10,num: 80}]}
--- {id: 3180,type: 30,level: 73, order: 18,num: 6,awards: [{item: 10,num: 50}]}
--- {id: 3190,type: 30,level: 79, order: 19,num: 2,awards: [{item: 60,awardId: 11010,num: 3}]}
--- {id: 3200,type: 30,level: 81, order: 20,num: 4,awards: [{item: 60,awardId: 11010,num: 2}]}
--- {id: 3210,type: 30,level: 85, order: 21,num: 6,awards: [{item: 60,awardId: 11010,num: 1}]}
--- {id: 3220,type: 30,level: 91, order: 22,num: 5,awards: [{item: 60,awardId: 50160,num: 1}]}
--- {id: 3230,type: 30,level: 96, order: 23,num: 8,awards: [{item: 60,awardId: 11572,num: 1}]}
--- {id: 3240,type: 30,level: 104, order: 24,num: 2,awards: [{item: 60,awardId: 50198,num: 200}]}
--- {id: 3250,type: 30,level: 106, order: 25,num: 3,awards: [{item: 60,awardId: 50198,num: 100}]}
--- {id: 3260,type: 30,level: 109, order: 26,num: 5,awards: [{item: 60,awardId: 50198,num: 80}]}
--- {id: 3270,type: 30,level: 114, order: 27,num: 6,awards: [{item: 60,awardId: 50198,num: 70}]}

#type=40 丰财聚宝-老虎机
#50%奖池
--- {id: 4001,type: 40,prop: 20,accTotal: [1100]}
#20%奖池
--- {id: 4002,type: 40,prop: 30,accTotal: [800]}
#10%奖池
--- {id: 4003,type: 40,prop: 100,accTotal: [400,700]}
#5%奖池
--- {id: 4004,type: 40,prop: 300,accTotal: [200,500,600]}
#随机高级卷轴
--- {id: 4005,type: 40,prop: 100,awards: [{item: 60,awardId: 11410,num: 1}],accTotal: [300,900]}
--- {id: 4006,type: 40,prop: 200,awards: [{item: 60,awardId: 11060,num: 1}]}
--- {id: 4007,type: 40,prop: 500,awards: [{item: 60,awardId: 10110,num: 1}]}
--- {id: 4008,type: 40,prop: 1900,awards: [{item: 60,awardId: 10180,num: 1}]}
--- {id: 4009,type: 40,prop: 1900,awards: [{item: 60,awardId: 11010,num: 1}]}
--- {id: 4010,type: 40,prop: 1700,awards: [{item: 60,awardId: 11090,num: 1}]}
--- {id: 4011,type: 40,prop: 1800,awards: [{item: 60,awardId: 580,num: 1}]}
--- {id: 4012,type: 40,prop: 1450,awards: [{item: 60,awardId: 10020,num: 5}]}
#type=50 金虎纳福
--- {id: 5010,type: 50,level: 10,order: 1,awards: [{item: 60,awardId: 11410,num: 1},{item: 10,num: 688},{item: 60,awardId: 11300,num: 1}]}
--- {id: 5020,type: 50,level: 20,order: 2,awards: [{item: 60,awardId: 10110,num: 9},{item: 10,num: 388}]}
--- {id: 5030,type: 50,level: 30,order: 3,awards: [{item: 60,awardId: 10180,num: 9},{item: 10,num: 288}]}
--- {id: 5040,type: 50,level: 40,order: 4,awards: [{item: 60,awardId: 11010,num: 5},{item: 10,num: 188}]}
--- {id: 5050,type: 50,level: 50,order: 5,awards: [{item: 60,awardId: 11090,num: 2},{item: 10,num: 158}]}
--- {id: 5060,type: 50,level: 60,order: 6,awards: [{item: 60,awardId: 10180,num: 1},{item: 10,num: 88}]}
--- {id: 5070,type: 50,level: 70,order: 7,awards: [{item: 60,awardId: 10020,num: 3},{item: 10,num: 58}]}