#魔法女巫配置
#CfgHolidayMagicWitch
key: 唯一
#基础材料
baseMaterial: [50478,50479,50480,50481]
#结果数量
resultSize: 3
#抽奖消耗
drawConsumptions:
  # treasureId: 抽奖消耗的法宝的id
  # num: 抽奖消耗的法宝的数量
  - {treasureId: 50478,num: 1}
  - {treasureId: 50479,num: 1}
  - {treasureId: 50480,num: 1}
  - {treasureId: 50481,num: 1}


#奖池
awardPool:
  - {id: 3010,type: 30,level: 0, order: 1,num: 1,awards: [{item: 60,awardId: 50482,num: 1}]}
  - {id: 3020,type: 30,level: 1, order: 2,num: 1,awards: [{item: 60,awardId: 50482,num: 1}]}
  - {id: 3030,type: 30,level: 2, order: 3,num: 1,awards: [{item: 60,awardId: 50483,num: 1}]}
  - {id: 3040,type: 30,level: 3, order: 4,num: 1,awards: [{item: 60,awardId: 50483,num: 1}]}
  - {id: 3050,type: 30,level: 4, order: 5,num: 1,awards: [{item: 60,awardId: 50484,num: 1}]}
  - {id: 3060,type: 30,level: 5, order: 6,num: 1,awards: [{item: 60,awardId: 50484,num: 1}]}
  - {id: 3070,type: 30,level: 6, order: 7,num: 1,awards: [{item: 60,awardId: 50485,num: 1}]}
  - {id: 3080,type: 30,level: 7, order: 8,num: 1,awards: [{item: 60,awardId: 50485,num: 1}]}
  - {id: 3090,type: 30,level: 8, order: 9,num: 1,awards: [{item: 60,awardId: 50486,num: 1}]}
  - {id: 3100,type: 30,level: 9, order: 10,num: 1,awards: [{item: 60,awardId: 50486,num: 1}]}
  - {id: 3110,type: 30,level: 10, order: 11,num: 1,awards: [{item: 60,awardId: 50487,num: 1}]}
  - {id: 3120,type: 30,level: 11, order: 12,num: 1,awards: [{item: 60,awardId: 50487,num: 1}]}
  - {id: 3130,type: 30,level: 12, order: 13,num: 1,awards: [{item: 60,awardId: 50488,num: 1}]}
  - {id: 3140,type: 30,level: 13, order: 14,num: 1,awards: [{item: 60,awardId: 50488,num: 1}]}
  - {id: 3150,type: 30,level: 14, order: 15,num: 1,awards: [{item: 60,awardId: 50489,num: 1}]}
  - {id: 3160,type: 30,level: 15, order: 16,num: 1,awards: [{item: 60,awardId: 50489,num: 1}]}
  - {id: 3170,type: 30,level: 16, order: 17,num: 1,awards: [{item: 60,awardId: 50490,num: 1}]}
  - {id: 3180,type: 30,level: 17, order: 18,num: 1,awards: [{item: 60,awardId: 50490,num: 1}]}
  - {id: 3190,type: 30,level: 18, order: 19,num: 1,awards: [{item: 60,awardId: 50491,num: 1}]}
  - {id: 3200,type: 30,level: 19, order: 20,num: 1,awards: [{item: 60,awardId: 50491,num: 1}]}
  - {id: 3210,type: 30,level: 20, order: 21,num: 1,awards: [{item: 60,awardId: 50492,num: 1}]}
  - {id: 3220,type: 30,level: 21, order: 22,num: 1,awards: [{item: 60,awardId: 50492,num: 1}]}
  - {id: 3230,type: 30,level: 22, order: 23,num: 1,awards: [{item: 60,awardId: 50493,num: 1}]}
  - {id: 3240,type: 30,level: 23, order: 24,num: 1,awards: [{item: 60,awardId: 50493,num: 1}]}
