# 城池配置
#CfgChengC
---
key: 9090
#城池守军列表
guCards:
  - {uid: 210809009900005,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900008,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900009,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900010,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900011,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900012,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900013,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900014,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人]}
  - {uid: 210809009900015,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900016,cards: [杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900017,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900018,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900019,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900020,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900021,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900022,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900023,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900024,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人]}
  - {uid: 210809009900025,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900026,cards: [杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900027,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900028,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900029,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900030,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900031,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900032,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900033,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900034,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人]}
  - {uid: 210809009900035,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900036,cards: [杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900037,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900038,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900039,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900040,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900041,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900042,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900043,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900044,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人]}
  - {uid: 210809009900045,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900046,cards: [杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900047,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900048,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900049,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900050,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900051,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900052,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900053,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900054,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人]}
  - {uid: 210809009900055,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900056,cards: [杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900057,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900058,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900059,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900060,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900061,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900062,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900063,cards: [桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师,白泽,灵牙仙,毗卢仙,姜文焕,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900064,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人]}
  - {uid: 210809009900065,cards: [云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙,乌云仙,长耳定光仙,余元,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900066,cards: [杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神,五夷散人,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}
  - {uid: 210809009900067,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,桃花星,申公豹,木吒,游法师,魔礼海,余化,蚕丛,灵宝法师]}
  - {uid: 210809009900068,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,云霄,崇黑虎,邓婵玉,龙吉公主,魔礼红,九尾狐王,无当圣母,螭龙]}
  - {uid: 210809009900069,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,杨任,胡喜媚,王天君,魔礼青,鄂顺,巡夜女使,星月女卫,夜游神]}
  - {uid: 210809009900070,cards: [姬发,雷震子,李靖,韦护,黄天化,窦荣,恶来,蜚廉,日游神,黄龙真人,金光仙,金箍仙,殷郊,邬文化,魔礼寿,土行孙,石矶娘娘,龟灵圣母,山魈王,虬首仙]}

...