#CfgSpecialHierarchyMap
#特产阶级对应
#TUCEQX
--- {fromSpecialId: 1,toSpecialId: 201}
--- {fromSpecialId: 2,toSpecialId: 202}
--- {fromSpecialId: 3,toSpecialId: 203}
--- {fromSpecialId: 4,toSpecialId: 204}
--- {fromSpecialId: 5,toSpecialId: 205}
--- {fromSpecialId: 6,toSpecialId: 206}
--- {fromSpecialId: 7,toSpecialId: 207}
--- {fromSpecialId: 8,toSpecialId: 208}
--- {fromSpecialId: 9,toSpecialId: 209}
--- {fromSpecialId: 10,toSpecialId: 210}
--- {fromSpecialId: 11,toSpecialId: 211}
--- {fromSpecialId: 12,toSpecialId: 212}
--- {fromSpecialId: 13,toSpecialId: 213}
--- {fromSpecialId: 14,toSpecialId: 214}
--- {fromSpecialId: 15,toSpecialId: 215}
--- {fromSpecialId: 16,toSpecialId: 216}
--- {fromSpecialId: 17,toSpecialId: 217}
--- {fromSpecialId: 18,toSpecialId: 218}
--- {fromSpecialId: 19,toSpecialId: 219}
--- {fromSpecialId: 20,toSpecialId: 220}
--- {fromSpecialId: 21,toSpecialId: 221}
--- {fromSpecialId: 22,toSpecialId: 222}
--- {fromSpecialId: 23,toSpecialId: 223}
--- {fromSpecialId: 24,toSpecialId: 224}
--- {fromSpecialId: 25,toSpecialId: 225}
--- {fromSpecialId: 31,toSpecialId: 231}
--- {fromSpecialId: 32,toSpecialId: 232}
--- {fromSpecialId: 33,toSpecialId: 233}
--- {fromSpecialId: 34,toSpecialId: 234}
--- {fromSpecialId: 35,toSpecialId: 235}
--- {fromSpecialId: 36,toSpecialId: 236}
--- {fromSpecialId: 37,toSpecialId: 237}
--- {fromSpecialId: 38,toSpecialId: 238}
--- {fromSpecialId: 39,toSpecialId: 239}
--- {fromSpecialId: 40,toSpecialId: 240}

--- {fromSpecialId: 201,toSpecialId: 301}
--- {fromSpecialId: 202,toSpecialId: 302}
--- {fromSpecialId: 203,toSpecialId: 303}
--- {fromSpecialId: 204,toSpecialId: 304}
--- {fromSpecialId: 205,toSpecialId: 305}
--- {fromSpecialId: 206,toSpecialId: 306}
--- {fromSpecialId: 207,toSpecialId: 307}
--- {fromSpecialId: 208,toSpecialId: 308}
--- {fromSpecialId: 209,toSpecialId: 309}
--- {fromSpecialId: 210,toSpecialId: 310}
--- {fromSpecialId: 211,toSpecialId: 311}
--- {fromSpecialId: 212,toSpecialId: 312}
--- {fromSpecialId: 213,toSpecialId: 313}
--- {fromSpecialId: 214,toSpecialId: 314}
--- {fromSpecialId: 215,toSpecialId: 315}
--- {fromSpecialId: 216,toSpecialId: 316}
--- {fromSpecialId: 217,toSpecialId: 317}
--- {fromSpecialId: 218,toSpecialId: 318}
--- {fromSpecialId: 219,toSpecialId: 319}
--- {fromSpecialId: 220,toSpecialId: 320}
--- {fromSpecialId: 221,toSpecialId: 321}
--- {fromSpecialId: 222,toSpecialId: 322}
--- {fromSpecialId: 223,toSpecialId: 323}
--- {fromSpecialId: 224,toSpecialId: 324}
--- {fromSpecialId: 225,toSpecialId: 325}
--- {fromSpecialId: 231,toSpecialId: 331}
--- {fromSpecialId: 232,toSpecialId: 332}
--- {fromSpecialId: 233,toSpecialId: 333}
--- {fromSpecialId: 234,toSpecialId: 334}
--- {fromSpecialId: 235,toSpecialId: 335}
--- {fromSpecialId: 236,toSpecialId: 336}
--- {fromSpecialId: 237,toSpecialId: 337}
--- {fromSpecialId: 238,toSpecialId: 338}
--- {fromSpecialId: 239,toSpecialId: 339}
--- {fromSpecialId: 240,toSpecialId: 340}

