#CfgAutoBuyHolidayProps
#一键购买节日道具
#TUCEQX
--- {id: 11440,name: 金元珠}
--- {id: 11450,name: 木元珠}
--- {id: 11460,name: 水元珠}
--- {id: 11470,name: 火元珠}
--- {id: 11480,name: 土元珠}
--- {id: 50217,name: 南瓜饼}
--- {id: 50218,name: 桂花糕}
--- {id: 50219,name: 桃花酥}
--- {id: 50170,name: 逗虎棒}
--- {id: 50222,name: 符•百毒不侵}
--- {id: 50308,name: 小扇子}
--- {id: 50309,name: 喷水手枪}
--- {id: 50310,name: 降温冰袋}
--- {id: 50311,name: 气球水蛋}
--- {id: 50321,name: 糍粑}
--- {id: 50322,name: 月饼}
--- {id: 50323,name: 醉蟹}
--- {id: 50401,name: 墨色锦鲤}
--- {id: 50402,name: 红白锦鲤}
--- {id: 50403,name: 三色锦鲤}
--- {id: 50404,name: 中华大锦鲤}
--- {id: 50433,name: 初级种子包}
--- {id: 50436,name: 初级肥料包}
--- {id: 50434,name: 中级种子包}
--- {id: 50437,name: 中级肥料包}
--- {id: 50435,name: 高级种子包}
--- {id: 50438,name: 高级肥料包}
--- {id: 50452,name: 蘑菇}
--- {id: 50453,name: 石蕊}
--- {id: 50454,name: 鹿草}
--- {id: 50455,name: 浆果}
--- {id: 50474,name: 小汤圆}
--- {id: 50475,name: 年糕}
--- {id: 50476,name: 鱼饼}
--- {id: 50203,name: 木条}
--- {id: 50204,name: 许愿蜡烛}
--- {id: 50205,name: 薄纸}
--- {id: 50171,name: 仙女棒}
--- {id: 10235,name: 窜天猴}
--- {id: 10220,name: 二踢脚}
--- {id: 50174,name: 大地红}
--- {id: 50497,name: 生肖碰碰卡}