# 炼宝炉产出法宝配置
#CfgLianBL
---
key: 唯一
#炼宝炉法宝列表
treasures: 
  #id法宝Id,name法宝，star星级
  - {id: 10,name: 财神珠,star: 5}
  - {id: 20,name: 乾坤图,star: 5}
  - {id: 30,name: 落宝金钱,star: 5}
  - {id: 50,name: 捆仙绳,star: 4}
  - {id: 60,name: 山河社稷图,star: 4}
  - {id: 70,name: 五彩石,star: 1}
  - {id: 80,name: 玉麒麟,star: 4}
  - {id: 90,name: 定风珠,star: 3}
  - {id: 110,name: 风火轮,star: 3}
  - {id: 120,name: 七香车,star: 3}
  - {id: 130,name: 青鸾,star: 2}
  - {id: 150,name: 四不像,star: 2}
  - {id: 160,name: 漫步靴,star: 1}
  - {id: 170,name: 醒酒毡,star: 1}
  - {id: 180,name: 送神符,star: 1}
  - {id: 190,name: 回马枪,star: 1}
  - {id: 205,name: 杏黄旗,star: 1}
  - {id: 210,name: 番天印,star: 5}
  - {id: 220,name: 打神鞭,star: 5}
  - {id: 230,name: 阴阳镜,star: 5}
  - {id: 240,name: 太极图,star: 5}
  - {id: 250,name: 诛仙剑,star: 5}
  - {id: 260,name: 九龙神火罩,star: 4}
  - {id: 270,name: 莫邪宝剑,star: 4}
  - {id: 280,name: 招魂幡,star: 4}
  - {id: 290,name: 戮仙剑,star: 4}
  - {id: 300,name: 攒心钉,star: 3}
  - {id: 310,name: 乾坤尺,star: 3}
  - {id: 320,name: 紫金钵盂,star: 3}
  - {id: 330,name: 紫绫仙衣,star: 3}
  - {id: 340,name: 绝仙剑,star: 3}
  - {id: 350,name: 乾坤弓,star: 2}
  - {id: 360,name: 震天箭,star: 2}
  - {id: 370,name: 红葫芦,star: 1}
  - {id: 380,name: 金葫芦,star: 2}
  - {id: 390,name: 陷仙剑,star: 2}
  - {id: 400,name: 混元金斗,star: 1}
  - {id: 410,name: 青云剑,star: 1}
  - {id: 420,name: 定神丹,star: 2}
  - {id: 430,name: 扫霞衣,star: 4}
  - {id: 10030,name: 混沌仙石,star: 3}
highLevelTreasures: # 6级后可产出
  - {id: 440,name: 五火神焰扇,star: 4}
  - {id: 450,name: 柴胡草,star: 2}
  - {id: 460,name: 如意乾坤袋,star: 1}
  - {id: 470,name: 太极符印,star: 1}
  - {id: 480,name: 火龙标,star: 2}
  - {id: 490,name: 百毒痘,star: 3}
lingshis: # 6级后可产出
  - {id: 810,name: 一星灵石,star: 1}
  - {id: 820,name: 二星灵石,star: 2}
  - {id: 830,name: 三星灵石,star: 3}
  - {id: 840,name: 四星灵石,star: 4}
  - {id: 850,name: 五星灵石,star: 5}

...