#商城配置
#CfgMall
key: 唯一
#商城物品最大可购数
maxBuyNum: 1000000
#神秘的数量
myteriousNum: 44
#神秘刷新需要的元宝
myteriousRefreshGold: 100
#神秘每日可刷新次数
mysteriousRefreshLimit: 1
#神秘3星灵石概率0.2
lsRate3: 2
#神秘4星灵石概率0.2
lsRate4: 2
#神秘5星灵石概率0.3
lsRate5: 3
#神秘聚灵旗概率0.4
jxqRate: 4
mallActivityBagMap: { 1291: 9080,1292: 9070 } #goodsId:activityType
#随机种子数(随机池大小：默认10000)
ramSeed: 10000
#神秘商品分组的数量（1-铜钱商品、2-元宝商品、3-钻石商品）
mallPartNums:
  - { part: 1,num: 16 }
  - { part: 2,num: 16 }
  - { part: 3,num: 12 }
#折扣类型：probability(占比随机总数比例:即概率(万分率))依据ramSend
#discount(折扣值),例:80,即为80%--remark(描述-方便查看)可为空"":例:有5%概率打7折
discounts:
  - { typeId: 1,probability: 500,discount: 70,remark: 有5%概率打7折 }
  - { typeId: 2,probability: 500,discount: 80,remark: 有5%概率打8折 }
  - { typeId: 3,probability: 1500,discount: 80,remark: 有15%概率打8折 }
  - { typeId: 4,probability: 1500,discount: 90,remark: 有15%概率打9折 }
  - { typeId: 5,probability: 2500,discount: 90,remark: 有25%概率打9折 }
#折扣组合：discountTypeArr折扣组:[typeId,typeId]->[1,3,5]:该part下存在，有5%概率打7折 有15%概率打8折 有25%概率打9折
discountGroups:
  - { discountGroupId: 1,types: [ 1,3,5 ] }
  - { discountGroupId: 2,types: [ 2,4 ] }
#isDiscount(是否有折扣): true有/false没有(discountGroupId不生效)--probability值为0 表示为固有商品
fsdlMysteriousMallProbs:
  - {id: 730010,part: 1,probability: 300,isDiscount: true,discountGroupId: 1 }
  - {id: 730020,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730030,part: 1,probability: 500,isDiscount: true,discountGroupId: 1 }
  - {id: 730040,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730050,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730060,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730070,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730080,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730090,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730100,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730110,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730120,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730130,part: 1,probability: 400,isDiscount: true,discountGroupId: 1 }
  - {id: 730140,part: 1,probability: 200,isDiscount: true,discountGroupId: 1 }
  - {id: 730150,part: 1,probability: 200,isDiscount: true,discountGroupId: 1 }
  - {id: 730160,part: 1,probability: 200,isDiscount: true,discountGroupId: 1 }
  - {id: 730170,part: 1,probability: 200,isDiscount: true,discountGroupId: 1 }
  - {id: 730180,part: 1,probability: 200,isDiscount: true,discountGroupId: 1 }
  - {id: 730190,part: 1,probability: 200,isDiscount: true,discountGroupId: 1 }
  - {id: 730200,part: 1,probability: 600,isDiscount: true,discountGroupId: 1 }
  - {id: 730210,part: 1,probability: 600,isDiscount: true,discountGroupId: 1 }
  - {id: 730220,part: 1,probability: 600,isDiscount: true,discountGroupId: 1 }
  - {id: 730230,part: 1,probability: 600,isDiscount: true,discountGroupId: 1 }
  - {id: 730240,part: 1,probability: 600,isDiscount: true,discountGroupId: 1 }
  - {id: 730250,part: 1,probability: 300,isDiscount: true,discountGroupId: 1 }
  - {id: 730260,part: 1,probability: 300,isDiscount: true,discountGroupId: 1 }
  - {id: 730270,part: 1,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730280,part: 1,probability: 0,isDiscount: false,discountGroupId: 0}
  - {id: 730290,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730300,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730310,part: 2,probability: 300,isDiscount: true,discountGroupId: 2 }
  - {id: 730320,part: 2,probability: 10,isDiscount: true,discountGroupId: 2 }
  - {id: 730330,part: 2,probability: 290,isDiscount: true,discountGroupId: 2 }
  - {id: 730340,part: 2,probability: 300,isDiscount: true,discountGroupId: 2 }
  - {id: 730350,part: 2,probability: 300,isDiscount: true,discountGroupId: 2 }
  - {id: 730360,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730370,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730380,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730390,part: 2,probability: 900,isDiscount: true,discountGroupId: 2 }
  - {id: 730400,part: 2,probability: 900,isDiscount: true,discountGroupId: 2 }
  - {id: 730410,part: 2,probability: 700,isDiscount: true,discountGroupId: 2 }
  - {id: 730420,part: 2,probability: 700,isDiscount: true,discountGroupId: 2 }
  - {id: 730430,part: 2,probability: 700,isDiscount: true,discountGroupId: 2 }
  - {id: 730440,part: 2,probability: 700,isDiscount: true,discountGroupId: 2 }
  - {id: 730450,part: 2,probability: 700,isDiscount: true,discountGroupId: 2 }
  - {id: 730460,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730470,part: 2,probability: 500,isDiscount: true,discountGroupId: 2 }
  - {id: 730480,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730490,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730500,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730510,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730520,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730530,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730540,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730550,part: 2,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730560,part: 3,probability: 800,isDiscount: false,discountGroupId: 0 }
  - {id: 730570,part: 3,probability: 500,isDiscount: false,discountGroupId: 0 }
  - {id: 730580,part: 3,probability: 1000,isDiscount: false,discountGroupId: 0 }
  - {id: 730590,part: 3,probability: 1000,isDiscount: false,discountGroupId: 0 }
  - {id: 730600,part: 3,probability: 300,isDiscount: false,discountGroupId: 0 }
  - {id: 730610,part: 3,probability: 800,isDiscount: false,discountGroupId: 0 }
  - {id: 730620,part: 3,probability: 300,isDiscount: false,discountGroupId: 0 }
  - {id: 730630,part: 3,probability: 900,isDiscount: false,discountGroupId: 0 }
  - {id: 730640,part: 3,probability: 800,isDiscount: false,discountGroupId: 0 }
  - {id: 730650,part: 3,probability: 700,isDiscount: false,discountGroupId: 0 }
  - {id: 730660,part: 3,probability: 500,isDiscount: false,discountGroupId: 0 }
  - {id: 730670,part: 3,probability: 300,isDiscount: false,discountGroupId: 0 }
  - {id: 730680,part: 3,probability: 600,isDiscount: false,discountGroupId: 0 }
  - {id: 730690,part: 3,probability: 500,isDiscount: false,discountGroupId: 0 }
  - {id: 730700,part: 3,probability: 400,isDiscount: false,discountGroupId: 0 }
  - {id: 730710,part: 3,probability: 300,isDiscount: false,discountGroupId: 0 }
  - {id: 730720,part: 3,probability: 200,isDiscount: false,discountGroupId: 0 }
  - {id: 730730,part: 3,probability: 100,isDiscount: false,discountGroupId: 0 }
  - {id: 730740,part: 3,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730750,part: 3,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730760,part: 3,probability: 0,isDiscount: false,discountGroupId: 0 }
  - {id: 730770,part: 3,probability: 0,isDiscount: false,discountGroupId: 0 }