#梦魇女娲庙配置文件
#CfgNightmareNvmEntity
key: 唯一

#捏土造人
#获得泥人进度值单位
clayFigurineValueUnit: 10000
#泥人进度值翻倍
clayFigurineValueDoubled: 3000000
#捏人需要的泥人进度值
pinchPeopleNeedValue: 150
#每日捏人有效次数
dayPinchPeopleValidTimes: 5
#捏人分数以及对应标识
pinchPeopleScore:
  - {sign: 1, score: 1}
  - {sign: 2, score: 1}
  - {sign: 3, score: 2}
  - {sign: 4, score: 3}
  - {sign: 5, score: 4}
  - {sign: 6, score: 5}
  - {sign: 7, score: 4}
  - {sign: 8, score: 3}
  - {sign: 9, score: 2}
  - {sign: 10, score: 1}
  - {sign: 11, score: 1}
#每日挑战奖励
dayChallengeAwards:
  - {minScore: 0, maxScore: 0.9, awards: [{awardId: 50198,item: 60,num: 10}]}
  - {minScore: 1, maxScore: 1.9, awards: [{awardId: 50232,item: 60,num: 1}]}
  - {minScore: 2, maxScore: 2.9, awards: [{awardId: 50233,item: 60,num: 1}]}
  - {minScore: 3, maxScore: 3.9, awards: [{awardId: 50234,item: 60,num: 1}]}
  - {minScore: 4, maxScore: 4.9, awards: [{awardId: 50235,item: 60,num: 1}]}
  - {minScore: 5, maxScore: 5, awards: [{awardId: 50236,item: 60,num: 1}]}
#每日礼包奖励以及概率
dayGiftAwards:
  #awardType奖励类型 10神格牌 20神将羁绊道具 30技能衍生残页
  - {progress: 6000, awardType: 10}
  - {progress: 2000, awardType: 20}
  - {progress: 2000, awardType: 30}
#捏人累计可领奖分数
pinchPeopleAwardNeedValue: 100
#累计分数奖励以及概率
totalScoreAwards:
  #awardType奖励类型 10神格牌 20神将羁绊道具 30技能衍生残页
  - {progress: 2500, awardType: 10}
  - {progress: 3750, awardType: 20}
  - {progress: 3750, awardType: 30}

#女娲集市
#最多可上架的商品数量
maxShelvesNum: 5
#租赁时间（单位：小时）
leaseTimeLimit: 8
#最多要价方式
maxPriceWay: 5
#租赁价格
rentalPrice: 16
#最多讨价数量:
maxBargainNum: 7
#讨价时间
bargainLimit: 2

#封神祭坛
#神格总进度
godheadTotalProgress: 8
#限制次数
exchangeLimitTimes: 2
#卡牌对应的神格牌
godHeadCard:
  - {cardId: 106,godHeadCardId: 50287}
  - {cardId: 204,godHeadCardId: 50288}
  - {cardId: 331,godHeadCardId: 50289}
  - {cardId: 435,godHeadCardId: 50290}
  - {cardId: 532,godHeadCardId: 50291}