#梦魇女娲庙产出道具配置
#CfgNightmareNvmOutputEntity
#type奖励类型 10神格牌 20神将羁绊道具 30技能衍生残页
--- {treasureId: 50237, cardId: 106, type: 20}
--- {treasureId: 50238, cardId: 204, type: 20}
--- {treasureId: 50239, cardId: 331, type: 20}
--- {treasureId: 50240, cardId: 435, type: 20}
--- {treasureId: 50241, cardId: 532, type: 20}
--- {treasureId: 50242, cardId: 106, type: 30}
--- {treasureId: 50243, cardId: 204, type: 30}
--- {treasureId: 50244, cardId: 331, type: 30}
--- {treasureId: 50245, cardId: 435, type: 30}
--- {treasureId: 50246, cardId: 532, type: 30}
--- {treasureId: 50247, cardId: 106, type: 10}
--- {treasureId: 50248, cardId: 106, type: 10}
--- {treasureId: 50249, cardId: 106, type: 10}
--- {treasureId: 50250, cardId: 106, type: 10}
--- {treasureId: 50251, cardId: 106, type: 10}
--- {treasureId: 50252, cardId: 106, type: 10}
--- {treasureId: 50253, cardId: 106, type: 10}
--- {treasureId: 50254, cardId: 106, type: 10}
--- {treasureId: 50255, cardId: 204, type: 10}
--- {treasureId: 50256, cardId: 204, type: 10}
--- {treasureId: 50257, cardId: 204, type: 10}
--- {treasureId: 50258, cardId: 204, type: 10}
--- {treasureId: 50259, cardId: 204, type: 10}
--- {treasureId: 50260, cardId: 204, type: 10}
--- {treasureId: 50261, cardId: 204, type: 10}
--- {treasureId: 50262, cardId: 204, type: 10}
--- {treasureId: 50263, cardId: 331, type: 10}
--- {treasureId: 50264, cardId: 331, type: 10}
--- {treasureId: 50265, cardId: 331, type: 10}
--- {treasureId: 50266, cardId: 331, type: 10}
--- {treasureId: 50267, cardId: 331, type: 10}
--- {treasureId: 50268, cardId: 331, type: 10}
--- {treasureId: 50269, cardId: 331, type: 10}
--- {treasureId: 50270, cardId: 331, type: 10}
--- {treasureId: 50271, cardId: 435, type: 10}
--- {treasureId: 50272, cardId: 435, type: 10}
--- {treasureId: 50273, cardId: 435, type: 10}
--- {treasureId: 50274, cardId: 435, type: 10}
--- {treasureId: 50275, cardId: 435, type: 10}
--- {treasureId: 50276, cardId: 435, type: 10}
--- {treasureId: 50277, cardId: 435, type: 10}
--- {treasureId: 50278, cardId: 435, type: 10}
--- {treasureId: 50279, cardId: 532, type: 10}
--- {treasureId: 50280, cardId: 532, type: 10}
--- {treasureId: 50281, cardId: 532, type: 10}
--- {treasureId: 50282, cardId: 532, type: 10}
--- {treasureId: 50283, cardId: 532, type: 10}
--- {treasureId: 50284, cardId: 532, type: 10}
--- {treasureId: 50285, cardId: 532, type: 10}
--- {treasureId: 50286, cardId: 532, type: 10}