#CfgPrestigeEntity
--- {prestigeId: 50193, businessGangId: 1000}
--- {prestigeId: 50194, businessGangId: 2000}
--- {prestigeId: 50195, businessGangId: 3000}
--- {prestigeId: 50196, businessGangId: 4000}
--- {prestigeId: 50197, businessGangId: 5000}