#游戏全局相关配置
#CfgTimeLimitTaskRules
---
groupId: 170000
maxTaskNum: 6
# 元宝加速(秒)
goldSpeedUpSeconds: 120
# 神行符加速(秒)
shenXSpeedUpSeconds: 1800
#条件对应陈功率
conditionRate: 25
# 星级成功率
starSuccessRate: [0,1,3,5,8]
# 卡牌等级间隔
cardLevelSpacing: 4
# 卡牌等级成功率
cardLevelRate: 1
# 精力重置时间
cardVigorRestHour: 8
#难度配置
#需要的体力needDice 需要的精力needCardVigor 满足的星级needStar: 派发时间(分)dispatchTime 等待时间(分)waitTime:
dispatchTaskConfigs:
  10: {needDice: 3,needCardVigor: 2,needStar: 2,skillLevels1: [1,2],skillLevels2: [1,2],skillLevels3: [1,2],dispatchTime: 30,waitTime: 99999}
  20: {needDice: 3,needCardVigor: 3,needStar: 3,skillLevels1: [2,3],skillLevels2: [2,3],skillLevels3: [2,3],dispatchTime: 60,waitTime: 99999}
  30: {needDice: 9,needCardVigor: 4,needStar: 4,skillLevels1: [3,4],skillLevels2: [3,4],skillLevels3: [3,4],dispatchTime: 180,waitTime: 99999}
  40: {needDice: 24,needCardVigor: 6,needStar: 5,skillLevels1: [4,5],skillLevels2: [4,5],skillLevels3: [4,5],dispatchTime: 480,waitTime: 99999}
#难度额外奖励配置
dispatchTaskExtraAward:
  10: {awards: [{item: 60, awardId: 10180, num: 1,probability: 10},{item: 60, awardId: 830, num: 1,probability: 10},{item: 60, awardId: 11010, num: 1,probability: 10},{item: 60, awardId: 11090, num: 1,probability: 10},{item: 10, num: 50,probability: 10},{item: 10, num: 30,probability: 15},{item: 20, num: 300000,probability: 10},{item: 20, num: 200000,probability: 15},{item: 60, awardId: 10020, num: 5,probability: 10}]}
  20: {awards: [{item: 60, awardId: 580, num: 1,probability: 5},{item: 60, awardId: 840, num: 1,probability: 5},{item: 60, awardId: 10180, num: 2,probability: 5},{item: 60, awardId: 830, num: 1,probability: 10},{item: 60, awardId: 11010, num: 2,probability: 8},{item: 60, awardId: 11090, num: 2,probability: 7},{item: 10, num: 90,probability: 10},{item: 10, num: 50,probability: 15},{item: 20, num: 600000,probability: 10},{item: 20, num: 400000,probability: 15},{item: 60, awardId: 10020, num: 8,probability: 10}]}
  30: {awards: [{item: 60, awardId: 11060, num: 1,probability: 3},{item: 60, awardId: 850, num: 1,probability: 5},{item: 60, awardId: 840, num: 1,probability: 8},{item: 60, awardId: 10180, num: 3,probability: 8},{item: 60, awardId: 11010, num: 3,probability: 6},{item: 60, awardId: 11090, num: 3,probability: 6},{item: 60, awardId: 10110, num: 1,probability: 6},{item: 10, num: 150,probability: 8},{item: 10, num: 100,probability: 10},{item: 20, num: 1200000,probability: 13},{item: 20, num: 900000,probability: 16},{item: 60, awardId: 10020, num: 13,probability: 11}]}
  40: {awards: [{item: 60, awardId: 11410, num: 1,probability: 3},{item: 60, awardId: 850, num: 1,probability: 5},{item: 60, awardId: 840, num: 2,probability: 8},{item: 60, awardId: 10180, num: 5,probability: 8},{item: 60, awardId: 11010, num: 5,probability: 6},{item: 60, awardId: 11090, num: 5,probability: 6},{item: 60, awardId: 10110, num: 2,probability: 6},{item: 10, num: 200,probability: 8},{item: 10, num: 160,probability: 10},{item: 20, num: 1600000,probability: 13},{item: 20, num: 1200000,probability: 16},{item: 60, awardId: 10020, num: 18,probability: 11}]}
#技能分级
levelSkills:
  1: [宝鉴,暴起,避雷,穿刺,得道,定风,法盾,返照,飞狙,疾驰,克敌,噬魂,无相,心止,修仙,真金,治愈,自愈,自在]
  2: [法身,飞行,护卫,回光,火球,枷锁,拦截,流毒,奇袭,祛毒,入痘,闪电,神剑,神疗,嗜血,死士,突袭,吸血,业火]
  3: [暴击,灵动,魅惑,灭魄,升仙,圣火,死斗,死咒,挑拨,偷营,威风,瘟君,巫医,妖术,怨灵,炙焰]
  4: [暗蛊,复活,刚毅,回魂,混元,力盾,联攻,龙息,强火,强金,强木,强水,强土,生火,生金,生木,生水,生土,双狙,销魂,兴法,主帅,钻地]
  5: [悲愤,超度,地劫,反间,反射,封神,封咒,蛊惑,鼓舞,激励,禁术,绝杀,雷电,连锁,袍泽,食尸,吸星,长生,招财,震慑,咒怨]

...