#游戏全局相关配置
#CfgTimeLimitTaskRules
#派礼小鹿派遣任务规则
---
groupId: 250000
#最大任务数
maxTaskNum: 3
#元宝加速(秒)
goldSpeedUpSeconds: 120
#神行符加速(秒)
shenXSpeedUpSeconds: 1800
#技能条件减少时间百分比
conditionRate: 15
#星级成功率
starSuccessRate: [100,100,100,100,100]
#星级减少时间
starReduceTime: [0,5,10,15,20]
#卡牌等级间隔
cardLevelSpacing: 4
#卡牌等级成功率
cardLevelRate: 1
#精力重置时间
cardVigorRestHour: 8
#天灵印额外次数
extraTimesForTianLY: 1
#地灵印额外次数
extraTimesForDiLY: 2
#最大排队任务数
maxQueuingTaskNum: 6
#派遣卡牌数
dispatchCardNum: 1
#最大等待任务数
maxWaitingTaskNum: 5
#派遣模式
dispatchMode: 20
#难度配置
#需要的体力needDice 需要的精力needCardVigor 满足的星级needStar: 派发时间(分)dispatchTime 等待时间(分)waitTime:
dispatchTaskConfigs:
  10: {needDice: 0,needCardVigor: 2,needStar: 0,skillLevels1: [1,2],dispatchTime: 120,waitTime: 9999}
  20: {needDice: 0,needCardVigor: 3,needStar: 0,skillLevels1: [2,3],dispatchTime: 240,waitTime: 9999}
  30: {needDice: 0,needCardVigor: 4,needStar: 0,skillLevels1: [3,4],dispatchTime: 360,waitTime: 9999}
  40: {needDice: 0,needCardVigor: 5,needStar: 0,skillLevels1: [4,5],dispatchTime: 480,waitTime: 9999}
#难度额外奖励配置
dispatchTaskExtraAward:
  10: {awards: [{item: 60, awardId: 50478, num: 1,probability: 25},{item: 60, awardId: 50479, num: 1,probability: 25},{item: 60, awardId: 50480, num: 1,probability: 25},{item: 60, awardId: 50481, num: 1,probability: 25}]}
  20: {awards: [{item: 60, awardId: 50478, num: 1,probability: 25},{item: 60, awardId: 50479, num: 1,probability: 25},{item: 60, awardId: 50480, num: 1,probability: 25},{item: 60, awardId: 50481, num: 1,probability: 25}]}
  30: {awards: [{item: 60, awardId: 50478, num: 1,probability: 25},{item: 60, awardId: 50479, num: 1,probability: 25},{item: 60, awardId: 50480, num: 1,probability: 25},{item: 60, awardId: 50481, num: 1,probability: 25}]}
  40: {awards: [{item: 60, awardId: 50478, num: 1,probability: 25},{item: 60, awardId: 50479, num: 1,probability: 25},{item: 60, awardId: 50480, num: 1,probability: 25},{item: 60, awardId: 50481, num: 1,probability: 25}]}
#技能分级
levelSkills:
  1: [宝鉴,暴起,避雷,穿刺,得道,定风,法盾,返照,飞狙,疾驰,克敌,噬魂,无相,心止,修仙,真金,治愈,自愈,自在]
  2: [法身,飞行,护卫,回光,火球,枷锁,拦截,流毒,奇袭,祛毒,入痘,闪电,神剑,神疗,嗜血,死士,突袭,吸血,业火]
  3: [暴击,灵动,魅惑,灭魄,升仙,圣火,死斗,死咒,挑拨,偷营,威风,瘟君,巫医,妖术,怨灵,炙焰]
  4: [暗蛊,复活,刚毅,回魂,混元,力盾,联攻,龙息,强火,强金,强木,强水,强土,生火,生金,生木,生水,生土,双狙,销魂,兴法,主帅,钻地]
  5: [悲愤,超度,地劫,反间,反射,封神,封咒,蛊惑,鼓舞,激励,禁术,绝杀,雷电,连锁,袍泽,食尸,吸星,长生,招财,震慑,咒怨]

...