# 魔王配置
#CfgGameMaou
---
key: 1000
#允许的参战卡牌数
cardLimit: 3
#免费次数
freeTimes: 25
#地灵印额外次数
extraTimesForDiLY: 5
#天灵印额外次数
extraTimesForTingLY: 5
#两轮间隔时间
intervalSeconds: 300
# 等级达到多少级的参与者可获得击杀奖励。!!!如果与其他特殊条件判定，由具体业务特殊处理。
killAwardsNeedLevel: 10
#魔王信息
maous:
  # initBlood: 初始血量
  # minTurn: 使用该魔王数据的最小轮次
  # maxTurn: 使用该魔王数据的最大轮次。999999相当于无限轮次
  # extraBloodPerTurn: 在轮次期间，每轮的血量加值
  # killAwards:击杀奖励
  - {id: 10010,initBlood: 400000000,minTurn: 1,maxTurn: 999999,extraBloodPerTurn: 0, killAwards: [{item: 60,awardId: 11010,num: 5},{item: 60,awardId: 10180,num: 3},{item: 60,awardId: 10020,num: 10},{item: 20,num: 100000},{item: 60,awardId: 11090,num: 1}]}
#目标奖励
targets:
  - {id: 100,blood: 50000,awards: [{item: 20,num: 200000}]}
  - {id: 110,blood: 100000,awards: [{item: 60,awardId: 11010,num: 5}]}
  - {id: 120,blood: 150000,awards: [{item: 20,num: 500000}]}
  - {id: 130,blood: 200000,awards: [{item: 60,awardId: 11010,num: 10}]}
  - {id: 140,blood: 250000,awards: [{item: 60,awardId: 10180,num: 9}]}
  - {id: 150,blood: 300000,awards: [{item: 60,awardId: 10110,num: 9}]}
  - {id: 160,blood: 350000,awards: [{item: 60,awardId: 11400,num: 1}]}
  - {id: 170,blood: 400000,awards: [{item: 60,awardId: 11060,num: 1}]}

#生效的技能:强金、强木、强水、强火、强土、联攻、嗜血、暴击、道法、太极
effectSkills:
  - 3119
  - 3120
  - 3121
  - 3122
  - 3123
  - 2201
  - 4203
  - 4104
  - 3126
  - 4116
#生效的组合：黄家军、陈塘家、梅山七怪
effectGroups:
  - 2002
  - 2003
  - 2010
...