#封神令配置
--- {id: 90010,name: 崇侯虎封神令,cardId: 325,deifyCardId: 10325}
--- {id: 90020,name: 杨戬封神令,cardId: 102,deifyCardId: 10102}
--- {id: 90030,name: 哪吒封神令,cardId: 201,deifyCardId: 10201}
--- {id: 90040,name: 张奎封神令,cardId: 527,deifyCardId: 10527}
--- {id: 90050,name: 孔雀明王封神令,cardId: 430,deifyCardId: 10430}
--- {id: 90060,name: 妲己入魔令,cardId: 301,deifyCardId: 10301}
--- {id: 90070,name: 玉鼎真人封神令,cardId: 247,deifyCardId: 10247}
--- {id: 90080,name: 姜子牙入圣令,cardId: 101,deifyCardId: 10101}
--- {id: 90090,name: 赵公明封神令,cardId: 302,deifyCardId: 10302}
--- {id: 90100,name: 韦护封神令,cardId: 106,deifyCardId: 10106}
--- {id: 90110,name: 袁洪封神令,cardId: 204,deifyCardId: 10204}
--- {id: 90120,name: 无当圣母封神令,cardId: 331,deifyCardId: 10331}
--- {id: 90130,name: 天花娘娘封神令,cardId: 435,deifyCardId: 10435}
--- {id: 90140,name: 龟灵圣母封神令,cardId: 532,deifyCardId: 10532}
--- {id: 90150,name: 赤精子封神令,cardId: 464,deifyCardId: 10464}
--- {id: 90160,name: 金睛白虎封神令,cardId: 142,deifyCardId: 10142}
--- {id: 90170,name: 孟章苍龙封神令,cardId: 236,deifyCardId: 10236}
--- {id: 90180,name: 重甲玄武封神令,cardId: 347,deifyCardId: 10347}
--- {id: 90190,name: 金銮火凤封神令,cardId: 401,deifyCardId: 10401}
#--- {id: 90200,name: 慈航道人封神令,cardId: 363,deifyCardId: 10363}
