#TODO
#需要参数：神仙概率
---
#策略名称
key: 5级城池_攻城振兴
#策略描述
desc: 按概率掉落一张本城可掉落的卡牌。每级别的城池对应一套概率；概率受神仙的影响
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors: 
  -
    key: 5星卡
    condition: {star: 5,include: [$城池卡牌集]}
    probability: {type: 1,value: 20}
  -
    key: 4星卡
    condition: {star: 4,include: [$城池卡牌集]}
    probability: {type: 1,value: 44}
  -
    key: 3星卡
    condition: {star: 3,include: [$城池卡牌集]}
    probability: {type: 1,value: 100}
...