#策略名称
key: 上仙礼包
#策略描述
desc: 按如下分组次序获得；分号前如果都获得了，则从分号后随机，否则随机一张分号前未拥有的；如果指定卡牌都拥有了，则随机一张指定卡。分组次序：101,201,302,401,502;102,202,301,402;501
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 1
    condition: {star: 5,include: [$0类卡],exclude: [$角色卡牌集]}
    probability: {type: 0,value: 100}
  - key: 2
    condition: {include: [杨戬,句芒,妲己,火灵圣母],exclude: [$角色卡牌集]}
    probability: {type: 0,value: 100}
  - key: 3
    condition: {include: [闻仲],exclude: [$角色卡牌集]}
    probability: {type: 0,value: 100}
  - key: 4
    condition: {include: [姜子牙,哪吒,赵公明,金銮火凤,黄飞虎,杨戬,句芒,妲己,火灵圣母,闻仲]}
    probability: {type: 0,value: 100}
...