#策略名称
key: 充值榜第一名加奖
#策略描述
desc: 开服第7周起，充值排行榜第一名奖励的四星卡调整为：必出没有的四星卡牌。（除许愿卡池外，如已经获得全部四星卡牌，则随机获得任意四星卡牌的灵石）
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 1
    condition: {star: 4,include: [$0类卡,$1类卡,$2类卡,$3类卡],exclude: [$角色卡牌集]}
    probability: {type: 0,value: 100}
  - key: 2
    condition: {star: 4,include: [$0类卡,$1类卡,$2类卡,$3类卡]}
    probability: {type: 0,value: 100}
...