#策略名称
key: 卡池_属性_10连抽补偿
#策略描述
desc: 按概率获得卡牌（way=0、1）。10连抽必出4星以上
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 4星卡
    condition: {star: 4,type: $卡包属性, include: [$0类卡,$1类卡,$可洗入卡池卡牌集],exclude: [$排除卡牌,黄龙真人]}
    probability: {type: 1,value: 100}
...