#策略名称
key: 太一府_20个
#策略描述
desc: 5个-随机一张1星卡（way=0）；10个-随机一张2星卡（way=0）；15个-随机一张3星卡（way=0）；20个-随机一张四星卡（way=0）；25个-随机一张五星卡（way=0，当拥有全部的way=0的五星卡时加入第六张卡牌进行随机）
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 四星卡
    condition: {star: 4,include: [$0类卡,$可洗入大地图卡牌集]}
    probability: {type: 0,value: 100}
...