#策略名称
key: 消费福利第2和3周
#策略描述
desc: 开服第2，3周避免出恶来,蜚廉
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 1
    condition: {star: 4,include: [$0类卡,$1类卡,$2类卡,$3类卡],exclude: [$角色卡牌集,恶来,蜚廉]}
    probability: {type: 0,value: 100}
  - key: 2
    condition: {star: 4,include: [$0类卡,$1类卡,$2类卡,$3类卡],exclude: [$角色卡牌集]}
    probability: {type: 0,value: 100}
  - key: 3
    condition: {star: 4,include: [$0类卡,$1类卡,$2类卡,$3类卡]}
    probability: {type: 0,value: 100}
...