#TODO
#需要参数：$重复数据
---
#策略名称
key: 福临轩_普通日期
#策略描述
desc: 随机一张四星卡（way=0、1）
selectors:
  - key: 4星卡
    condition: {star: 4,include: [$0类卡,$1类卡],exclude: [$排除卡牌]}
    #type:概率类型0|1。0=真随机;1=伪随机。 value:概率[0,100]，maxTimes:保底策略，可选参数，最多多少次后必然命中。
    probability: {type: 0,value: 100}
...