#策略名称
key: 聚灵
#策略描述
desc: 指定可兑换的卡牌
#结果限制
maxSize: 1
selectors:
  - key: 1
    condition: {star: 5,include: [$0类卡]}
    #type:概率类型0|1。0=真随机;1=伪随机。 value:概率[0,100]，maxTimes:保底策略，可选参数，最多多少次后必然命中。
    probability: {type: 0,value: 100}
...