#策略名称
key: 聚贤卡池_聚贤总等级[1,10]
#策略描述
desc: 随机卡牌
#结果限制
maxSize: 1
#5星以上卡牌不超过1张
resultRules: [{star: 5,maxSize: 1}]
selectors:
  - key: 3星卡
    condition: {star: 3,include: [$0类卡,$可洗入大地图卡牌集],exclude: [黄天禄，苏全忠，玄武仙师]}
    probability: { type: 0,value: 5 }
  - key: 2星卡
    condition: {star: 2,include: [$0类卡,$可洗入大地图卡牌集]}
    probability: { type: 0,value: 47.36 }
  - key: 1星卡
    condition: {star: 1,include: [$0类卡,$可洗入大地图卡牌集]}
    probability: {type: 0,value: 100}
...