#TODO
---
#策略名称
key: 聚贤庄_前两张卡
#策略描述
desc: 随机2张本城可掉落的卡牌，1张非本城掉落的卡牌（way=0）;随机的3张卡牌4星以上卡牌不超过1张；掉落的概率更城池的级别、聚贤庄的等级有关
#结果限制 返回2张卡
maxSize: 2
#4星以上卡牌不超过1张
resultRules: [{star: 4,maxSize: 1}]
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 1
    requestSize: 2
    subStrategy: 聚贤庄_前两张每张卡
    probability: {type: 0,value: 100}
...