#策略名称
key: 聚贤庄_第三张卡
#策略描述
desc: 按概率掉落随机卡
#结果限制
maxSize: 1
#【请把最好的卡牌排在最前面，选卡时候依次从上往下执行，选择到满足结果要求的最大值后，将不再继续选择】
selectors:
  - key: 5星卡
    condition: {star: 5,include: [$0类卡,$可洗入大地图卡牌集],exclude: [$前几张卡]}
    probability: {type: 0,value: $5星概率}
  - key: 4星卡
    condition: {star: 4,include: [$0类卡,$可洗入大地图卡牌集],exclude: [$前几张卡]}
    probability: {type: 0,value: $4星概率}
  - key: 3星卡
    condition: {star: 3,include: [$0类卡,$可洗入大地图卡牌集],exclude: [$前几张卡]}
    probability: {type: 0,value: $3星概率}
  - key: 2星卡
    condition: {star: 2,include: [$0类卡,$可洗入大地图卡牌集],exclude: [$前几张卡]}
    probability: {type: 0,value: $2星概率}
  - key: 1星卡
    condition: {star: 1,include: [$0类卡,$可洗入大地图卡牌集],exclude: [$前几张卡]}
    probability: {type: 0,value: 100}
...