#策略名称
key: 魔王
#策略描述
desc: 随机一张4星卡（way=0，1）
#结果限制
maxSize: 1
selectors:
  - key: 1
    requestSize: 1
    condition: {star: 4,include: [$0类卡,$1类卡],exclude: [$排除卡牌]}
    #type:概率类型0|1。0=真随机;1=伪随机。 value:概率[0,100]，maxTimes:保底策略，可选参数，最多多少次后必然命中。
    probability: {type: 0,value: 100}
...