#卡牌组合
#CfgCardGroup.java
key: 唯一
cardGroups:
- {id: 2001,name: 十绝阵,shortName: 十绝阵,memo: "两人以上在场，每回合给对方召唤师造成在场十绝阵成员总星级*150的伤害。"}
- {id: 2002,name: 黄家军,shortName: 黄家军,memo: "两人以上在场，攻击各加300。"}
- {id: 2003,name: 陈塘家,shortName: 陈塘家,memo: "两人以上在场，阵中全体卡牌攻防各加100。"}
- {id: 2004,name: 九曲黄河阵,shortName: 黄河阵,memo: "三人同时在场，每回合将己方召唤师血量补满。"}
- {id: 2005,name: 迷魂阵,shortName: 迷魂阵,memo: "三人同时在场，对方场上全体卡牌特技失效。"}
- {id: 2006,name: 四大天王,shortName: 四大天王,memo: "三人在场，对方所有卡牌攻防永久各减150，四人同时在场，攻防永久各减300。"}
- {id: 2007,name: 哼哈二将,shortName: 哼哈二将,memo: "两人同时在场，每回合使对方场上攻防最高的卡牌攻防值永久减半。"}
- {id: 2008,name: 千里眼顺风耳,shortName: 二绝,memo: "两人同时在场，对方法术值永久损失1。"}
- {id: 2009,name: 九龙岛四圣,shortName: 九龙四圣,memo: "两人在场，随机拉一张卡牌上场。三人以上在场，随机拉卡牌将空位填满。"}
- {id: 2010,name: 梅山七怪,shortName: 梅山七怪,memo: "两人在场，每人攻防各加100，每多一人在场攻防再加100。"}
- {id: 2011,name: 左右门神,shortName: 左右门神,memo: "两人同时在场，全体上场卡牌防御值各加150。"}
- {id: 2012,name: 四海龙王,shortName: 四海龙王,memo: "三个以上在场，每人向对位卡牌施加威风技能。（无视金刚效果，可被回光）"}
- {id: 2013,name: 晁式兄弟,shortName: 兄弟同心,memo: "两人同时在场，直接杀死对方场上防御最低的卡牌，无视金刚。"}
- {id: 2014,name: 殷洪四天君,shortName: 殷门诀,memo: "三人以上在场，销毁对方一张坟场牌。四名以上在场，销毁对方两张坟场卡。"}
- {id: 2015,name: 神力横扫,shortName: 神力横扫,memo: "两人同时在场，给场上所有敌方卡牌（不含云台）施加一次攻击，伤害为两人之中的较低攻击力。"}
- {id: 2016,name: 闻仲四天君,shortName: 太师门,memo: "两人以上在场，该回合为我方全体卡牌追加无相技能，三名以上全体卡牌追加金刚技能。"}
- {id: 2017,name: 古兽来袭,shortName: 古兽来袭,memo: "三张以上在场，随机杀死一张受到过永远伤害的卡牌。"}
- {id: 2020,name: 上古神力,shortName: 上古神力,memo: "两人在场，将敌方所有地面卡牌送入坟场，一次战斗触发一次。两人在场，该回合对敌方地面卡牌造成一次在场成员中较低攻击值的伤害。"}