#卡牌
#CfgCard
key: 唯一
skillGroupActiveGold: 1000
#招财技能金币收益+100%
zcCopperAddRate: 100
#技能更换限制
skillScrollUseLimitPerCard: 2
skillChangePrice: [0,10,20,50,100] #更换技能价格
cardsToPool: [姬昌,道行天尊,姜桓楚,女娲化蛇,崇侯虎,鄂崇禹,纣王,张奎,惧留孙,周公旦,南宫适,恶来,蜚廉,黄龙真人,袁洪,琵琶精,哪吒,木吒,羽翼仙,菡芝仙,女娲灵守,九天玄女,碧霄,九尾狐王,玄武仙师,狰狞,金光圣母,罗宣,天花娘娘,山神,龙须虎,夔牛,应龙,凿齿,金睛白虎,苏全忠,周信,腾蛇,修蛇,大风,重甲玄武,猰貐,九婴,度厄真人,封豨,徐芳,敖丙,李奇,嘲风,朱天麟,孙焰红,杨文辉,巫医,巡海夜叉,黄天禄,广法天尊,黄明,周纪,龙环,吴谦,黄飞彪,郑伦,陈奇,马元,栢鉴,鸿鹄,小哪吒,火尖枪锻将,混天绫灵神,乾坤圈精元,牛金牛,斥候,千里马,鹿台亲兵,卫队长,哮天犬,彩云仙子,冤魂,食尸鬼,姜环,邱引,烛龙,殷素知,灵坛护法,蚊道人,金眼驼,姜皇后,马善,普贤真人,太颠,鲁雄,袁福通,闳夭,辛免,姮娥仙子,地走星,萧升,崇应彪,玄坛黑虎,袁福通,太阴星君,崇应鸾,金灵圣母,高继能,陈九公,赤精子,望帝,万年鼋龙,陈桐,闻聘,郭宸,犰狳]
cardsToMap: [周公旦,南宫适,恶来,蜚廉,黄龙真人,袁洪,琵琶精,哪吒,木吒,羽翼仙,菡芝仙,女娲灵守,九天玄女,碧霄,九尾狐王,玄武仙师,狰狞,金光圣母,罗宣,天花娘娘,山神,龙须虎,夔牛,应龙,虚日鼠,云霞兽,魔童,赤云,五色神牛,凿齿,苏全忠,周信,腾蛇,修蛇,大风,猰貐,九婴,度厄真人,封豨,徐芳,敖丙,李奇,嘲风,朱天麟,伯夷,叔齐,孙焰红,杨文辉,巫医,巡海夜叉,黄天禄,黄明,周纪,龙环,吴谦,黄飞彪,白云童子,白莲童子,金霞童子,金毛童子,水火童子,郑伦,陈奇,马元,栢鉴,鸿鹄,小哪吒,火尖枪锻将,混天绫灵神,乾坤圈精元,牛金牛,斥候,千里马,鹿台亲兵,卫队长,哮天犬,彩云仙子,冤魂,食尸鬼,姜环,邱引,烛龙,殷素知,灵坛护法,蚊道人,金眼驼,姜皇后,马善,普贤真人,太颠,鲁雄,袁福通,闳夭,辛免,姮娥仙子,地走星,萧升,崇应彪,玄坛黑虎,袁福通,崇应鸾,高继能,陈九公,望帝,万年鼋龙,陈桐,闻聘,郭宸,犰狳]
#卡牌升级数据配置
cardUpdateData: #卡牌等级上限
  cardTopLevel: 40
  #卡牌阶数上限
  cardTopHierarchy: 10
  #每个元素消耗多少铜钱
  copperPerEle: 8000
  #一个元素对应多少经验，与卡牌非同属性元素获得经验的减半
  expPerEle: 1000
  #一星卡牌前十级升级所需经验
  needExp1: [ 100, 200, 400, 800, 1600, 2400, 3600, 5400, 8100, 12150 ] #34750
  tenExp1: 34750
  #二星卡牌前十级升级所需经验
  needExp2: [ 200, 400, 800, 1600, 3200, 4800, 7200, 10800, 16200, 24300 ] # 69500
  tenExp2: 69500
  #三星卡牌前十级升级所需经验
  needExp3: [ 400, 800, 1600, 3200, 6400, 9600, 14400, 21600, 32400, 48600 ] # 139000
  tenExp3: 139000
  #四星卡牌前十级升级所需经验
  needExp4: [ 800, 1600, 3200, 6400, 12800, 19200, 28800, 43200, 64800, 97200 ] # 278000
  tenExp4: 278000
  #五星卡牌前十级升级所需经验
  needExp5: [ 1600, 3200, 6400, 12800, 25600, 38400, 57600, 86400, 129600, 194400 ] # 556000
  tenExp5: 556000