#CfgFlockStarBook
#群星图册
#TUCEQX
--- {id: 101,name: 姜子牙}
--- {id: 102,name: 杨戬}
--- {id: 105,name: 李靖}
--- {id: 108,name: 周公旦}
--- {id: 109,name: 金吒}
--- {id: 114,name: 南宫适}
--- {id: 126,name: 姬昌}
--- {id: 127,name: 恶来}
--- {id: 128,name: 蜚廉}
--- {id: 130,name: 鱼凫}
--- {id: 132,name: 道行天尊}
--- {id: 137,name: 毕环}
--- {id: 138,name: 辛环}
--- {id: 139,name: 亢金龙}
--- {id: 140,name: 虚日鼠}
--- {id: 142,name: 金睛白虎}
--- {id: 143,name: 李奇}
--- {id: 144,name: 黄天禄}
--- {id: 145,name: 龙环}
--- {id: 146,name: 金毛童子}
--- {id: 148,name: 乾坤圈精元}
--- {id: 149,name: 牛金牛}
--- {id: 150,name: 斥候}
--- {id: 151,name: 金眼驼}
--- {id: 152,name: 普贤真人}
--- {id: 201,name: 哪吒}
--- {id: 202,name: 句芒}
--- {id: 204,name: 袁洪}
--- {id: 206,name: 木吒}
--- {id: 209,name: 琵琶精}
--- {id: 225,name: 羽翼仙}
--- {id: 226,name: 姜桓楚}
--- {id: 227,name: 菡芝仙}
--- {id: 233,name: 毕方}
--- {id: 236,name: 孟章苍龙}
--- {id: 237,name: 刘甫}
--- {id: 240,name: 张节}
--- {id: 241,name: 角木蛟}
--- {id: 242,name: 女娲化蛇}
--- {id: 244,name: 云霞兽}
--- {id: 246,name: 苏全忠}
--- {id: 248,name: 周信}
--- {id: 249,name: 腾蛇}
--- {id: 250,name: 叔齐}
--- {id: 251,name: 巫医}
--- {id: 252,name: 吴谦}
--- {id: 253,name: 白莲童子}
--- {id: 254,name: 鸿鹄}
--- {id: 255,name: 板角青牛}
--- {id: 256,name: 姜环}
--- {id: 257,name: 蚊道人}
--- {id: 261,name: 姜皇后}
--- {id: 301,name: 妲己}
--- {id: 302,name: 赵公明}
--- {id: 307,name: 九天玄女}
--- {id: 309,name: 碧霄}
--- {id: 325,name: 崇侯虎}
--- {id: 326,name: 九尾狐王}
--- {id: 328,name: 玉面银狐}
--- {id: 329,name: 碧云}
--- {id: 330,name: 厉鬼}
--- {id: 332,name: 雉鸡精}
--- {id: 333,name: 韩毒龙}
--- {id: 334,name: 敖广}
--- {id: 335,name: 敖闰}
--- {id: 336,name: 敖顺}
--- {id: 342,name: 陶荣}
--- {id: 343,name: 箕水豹}
--- {id: 344,name: 玄武仙师}
--- {id: 345,name: 狰狞}
--- {id: 347,name: 重甲玄武}
--- {id: 348,name: 敖丙}
--- {id: 349,name: 杨文辉}
--- {id: 350,name: 巡海夜叉}
--- {id: 351,name: 广法天尊}
--- {id: 352,name: 黄明}
--- {id: 353,name: 白云童子}
--- {id: 355,name: 混天绫灵神}
--- {id: 356,name: 彩云仙子}
--- {id: 357,name: 冤魂}
--- {id: 360,name: 玄坛黑虎}
--- {id: 401,name: 金銮火凤}
--- {id: 402,name: 火灵圣母}
--- {id: 403,name: 金光圣母}
--- {id: 412,name: 罗宣}
--- {id: 425,name: 鄂崇禹}
--- {id: 428,name: 赤云}
--- {id: 430,name: 孔雀明王}
--- {id: 432,name: 薛恶虎}
--- {id: 434,name: 敖钦}
--- {id: 435,name: 天花娘娘}
--- {id: 437,name: 邓忠}
--- {id: 438,name: 魔童}
--- {id: 439,name: 尾火虎}
--- {id: 444,name: 孙焰红}
--- {id: 445,name: 嘲风}
--- {id: 446,name: 朱天麟}
--- {id: 447,name: 伯夷}
--- {id: 448,name: 周纪}
--- {id: 449,name: 水火童子}
--- {id: 450,name: 刘环}
--- {id: 456,name: 小哪吒}
--- {id: 457,name: 火尖枪锻匠}
--- {id: 458,name: 食尸鬼}
--- {id: 460,name: 马善}
--- {id: 501,name: 闻仲}
--- {id: 502,name: 黄飞虎}
--- {id: 503,name: 山神}
--- {id: 511,name: 龙须虎}
--- {id: 526,name: 比干}
--- {id: 527,name: 张奎}
--- {id: 529,name: 晁田}
--- {id: 530,name: 晁雷}
--- {id: 531,name: 尤浑}
--- {id: 535,name: 吕岳}
--- {id: 536,name: 叛逆童子}
--- {id: 537,name: 应龙}
--- {id: 538,name: 五色神牛}
--- {id: 539,name: 氐土貉}
--- {id: 540,name: 惧留孙}
--- {id: 543,name: 徐芳}
--- {id: 544,name: 黄飞彪}
--- {id: 545,name: 金霞童子}
--- {id: 546,name: 雷开}
--- {id: 548,name: 千里马}
--- {id: 549,name: 鹿台亲兵}
--- {id: 550,name: 卫队长}
--- {id: 551,name: 哮天犬}
--- {id: 552,name: 邱引}
--- {id: 553,name: 烛龙}