#CfgSpecialGodCardEntity
#特殊封神卡牌
--- {cardId: 10331,name: 无当圣母,star: 5}
--- {cardId: 10204,name: 袁洪,star: 5}
--- {cardId: 10106,name: 韦护,star: 5}
--- {cardId: 10435,name: 天花娘娘,star: 5}
--- {cardId: 10532,name: 龟灵圣母,star: 5}