---
#CfgLeaderCardSkill
#专属技能
exclusiveSkills: ["影随","镜像","让位","斥退","落羽","太极","金身","王者","痊愈"]
skillTrees:
#金
  - property: 10
    page: 1
    tree:
      "自愈": ""
      "修仙": "自愈"
      "得道": "自愈"
      "无相": "自愈"
      "升仙": "修仙"
      "克敌": "得道,无相"
      "飞行": "克敌"
      "法盾": "克敌"
      "疾驰": "克敌"
      "联攻": "飞行,法盾,疾驰"
      "封神": "联攻"
      "吸星": "联攻"
      "招财": "吸星"
  - property: 10
    page: 2
    tree:
        "暴起": ""
        "嗜血": "暴起"
        "穿刺": "暴起"
        "死斗": "暴起"
        "神剑": "嗜血"
        "奇袭": "穿刺"
        "死士": "死斗"
        "突袭": "神剑,奇袭"
        "暴击": "突袭"
        "龙息": "突袭"
        "鼓舞": "龙息"
        "激励": "龙息"
        "震慑": "鼓舞"
  - property: 10
    page: 3
    tree:
        "心止": ""
        "避雷": "心止"
        "自在": "心止"
        "真金": "心止"
        "闪电": "避雷"
        "枷锁": "自在"
        "宝鉴": "真金"
        "返照": "闪电,枷锁,宝鉴"
        "偷营": "返照"
        "主帅": "返照"
        "蛊惑": "偷营,主帅"
        "雷电": "蛊惑"
        "连锁": "蛊惑"
  - property: 10
    page: 4
    tree:
        "定风": ""
        "力盾": "定风"
        "护卫": "定风"
        "威风": "定风"
        "回光": "力盾,护卫,威风"
        "强水": "回光"
        "法身": "回光"
        "生水": "回光"
        "反射": "强水,法身,生水"
        "封咒": "反射"
        "长生": "反射"
        "超度": "反射"
        "禁术": "封咒"
#木
  - property: 20
    page: 1
    tree:
        "自愈": ""
        "修仙": "自愈"
        "得道": "自愈"
        "无相": "自愈"
        "升仙": "修仙"
        "克敌": "得道,无相"
        "飞行": "克敌"
        "法盾": "克敌"
        "疾驰": "克敌"
        "联攻": "飞行,法盾,疾驰"
        "封神": "联攻"
        "吸星": "联攻"
        "招财": "吸星"
  - property: 20
    page: 2
    tree:
       "暴起": ""
       "护卫": "暴起"
       "治愈": "暴起"
       "祛毒": "暴起"
       "穿刺": "护卫"
       "神疗": "治愈"
       "流毒": "祛毒"
       "死士": "穿刺,神疗"
       "入痘": "流毒"
       "刚毅": "死士"
       "回魂": "死士"
       "鼓舞": "回魂"
       "激励": "回魂"
       "震慑": "鼓舞"
  - property: 20
    page: 3
    tree:
       "心止": ""
       "自在": "心止"
       "避雷": "心止"
       "真金": "心止"
       "枷锁": "自在"
       "拦截": "避雷"
       "灵动": "真金"
       "返照": "枷锁,拦截,灵动"
       "挑拨": "返照"
       "复活": "返照"
       "蛊惑": "挑拨,复活"
       "连锁": "蛊惑"
       "反间": "蛊惑"
  - property: 20
    page: 4
    tree:
       "定风": ""
       "灭魄": "定风"
       "力盾": "定风"
       "飞狙": "定风"
       "回光": "灭魄,力盾"
       "双狙": "飞狙"
       "强火": "回光"
       "法身": "回光"
       "生火": "回光"
       "反射": "强火,法身,生火"
       "封咒": "反射"
       "长生": "反射"
       "超度": "反射"
       "禁术": "封咒"
#水
  - property: 30
    page: 1
    tree:
        "自愈": ""
        "修仙": "自愈"
        "得道": "自愈"
        "无相": "自愈"
        "升仙": "修仙"
        "克敌": "得道,无相"
        "飞行": "克敌"
        "法盾": "克敌"
        "疾驰": "克敌"
        "联攻": "飞行,法盾,疾驰"
        "封神": "联攻"
        "吸星": "联攻"
        "招财": "吸星"
  - property: 30
    page: 2
    tree:
       "暴起": ""
       "治愈": "暴起"
       "护卫": "暴起"
       "流毒": "暴起"
       "神疗": "治愈"
       "灵动": "护卫"
       "入痘": "流毒"
       "吸血": "神疗,灵动"
       "巫医": "入痘"
       "销魂": "吸血"
       "回魂": "吸血"
       "鼓舞": "回魂"
       "激励": "回魂"
       "震慑": "鼓舞"
  - property: 30
    page: 3
    tree:
       "心止": ""
       "避雷": "心止"
       "自在": "心止"
       "真金": "心止"
       "闪电": "避雷"
       "噬魂": "自在"
       "拦截": "真金"
       "返照": "闪电,噬魂,拦截"
       "挑拨": "返照"
       "魅惑": "返照"
       "妖术": "返照"
       "蛊惑": "挑拨,魅惑,妖术"
       "雷电": "蛊惑"
       "反间": "蛊惑"
       "绝杀": "蛊惑"
  - property: 30
    page: 4
    tree:
       "定风": ""
       "死咒": "定风"
       "宝鉴": "定风"
       "怨灵": "定风"
       "回光": "死咒,宝鉴"
       "咒怨": "怨灵"
       "强木": "回光"
       "法身": "回光"
       "生木": "回光"
       "反射": "强木,法身,生木"
       "封咒": "反射"
       "长生": "反射"
       "超度": "反射"
       "禁术": "封咒"
#火
  - property: 40
    page: 1
    tree:
        "自愈": ""
        "修仙": "自愈"
        "得道": "自愈"
        "无相": "自愈"
        "克敌": "得道,无相"
        "飞行": "克敌"
        "法盾": "克敌"
        "疾驰": "克敌"
        "联攻": "飞行,法盾,疾驰"
        "封神": "联攻"
        "吸星": "联攻"
        "招财": "吸星"
  - property: 40
    page: 2
    tree:
       "暴起": ""
       "祛毒": "暴起"
       "奇袭": "暴起"
       "火球": "暴起"
       "流毒": "祛毒"
       "穿刺": "奇袭"
       "业火": "火球"
       "死士": "流毒,穿刺"
       "圣火": "业火"
       "瘟君": "死士"
       "巫医": "死士"
       "鼓舞": "巫医"
       "激励": "巫医"
       "震慑": "鼓舞"
  - property: 40
    page: 3
    tree:
       "心止": ""
       "避雷": "心止"
       "自在": "心止"
       "真金": "心止"
       "闪电": "避雷"
       "枷锁": "自在"
       "吸血": "真金"
       "返照": "闪电,枷锁,吸血"
       "魅惑": "返照"
       "噬魂": "返照"
       "妖术": "返照"
       "蛊惑": "魅惑,噬魂,妖术"
       "雷电": "蛊惑"
       "连锁": "蛊惑"
       "绝杀": "蛊惑"
  - property: 40
    page: 4
    tree:
       "定风": ""
       "护卫": "定风"
       "死咒": "定风"
       "怨灵": "定风"
       "偷营": "护卫,死咒"
       "咒怨": "怨灵"
       "强土": "偷营"
       "法身": "偷营"
       "生土": "偷营"
       "反射": "强土,法身,生土"
       "封咒": "反射"
       "长生": "反射"
       "超度": "反射"
       "禁术": "封咒"
#土
  - property: 50
    page: 1
    tree:
        "自愈": ""
        "修仙": "自愈"
        "得道": "自愈"
        "无相": "自愈"
        "克敌": "得道,无相"
        "飞行": "克敌"
        "法盾": "克敌"
        "疾驰": "克敌"
        "联攻": "飞行,法盾,疾驰"
        "封神": "联攻"
        "吸星": "联攻"
        "招财": "吸星"
  - property: 50
    page: 2
    tree:
       "暴起": ""
       "死斗": "暴起"
       "穿刺": "暴起"
       "飞狙": "暴起"
       "死士": "死斗"
       "突袭": "穿刺"
       "双狙": "飞狙"
       "嗜血": "死士,突袭"
       "暴击": "嗜血"
       "龙息": "嗜血"
       "鼓舞": "龙息"
       "激励": "龙息"
       "震慑": "鼓舞"
  - property: 50
    page: 3
    tree:
       "心止": ""
       "避雷": "心止"
       "自在": "心止"
       "真金": "心止"
       "闪电": "避雷"
       "入痘": "自在"
       "宝鉴": "真金"
       "返照": "闪电,入痘,宝鉴"
       "钻地": "返照"
       "瘟君": "返照"
       "刚毅": "返照"
       "蛊惑": "钻地,瘟君,刚毅"
       "雷电": "蛊惑"
       "地劫": "蛊惑"
  - property: 50
    page: 4
    tree:
       "定风": ""
       "护卫": "定风"
       "灭魄": "定风"
       "威风": "定风"
       "噬魂": "护卫,灭魄,威风"
       "强金": "噬魂"
       "法身": "噬魂"
       "生金": "噬魂"
       "反射": "强金,法身,生金"
       "封咒": "反射"
       "长生": "反射"
       "超度": "反射"
       "禁术": "封咒"

...