---
groupId: 22000
# 当isValid 设置有false时只允许获取奖励，不允许用来生成任务
tasks: 
#固定类 22010-22099
  - {id: 22010,type: 30,name: "今日首次登录游戏",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22011,type: 30,name: "消耗5个元素升级卡牌",value: 5,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22012,type: 30,name: "消耗60点体力",value: 60,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22013,type: 30,name: "领取1次封神台积分",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22014,type: 30,name: "使用1次地图法宝",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22015,type: 30,name: "使用1个战斗法宝",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22016,type: 30,name: "累计铜钱收益%s万",value: null,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22017,type: 30,name: "进行5次练兵",value: 5, awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22018,type: 30,name: "到商城花费元宝购物1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22019,type: 30,name: "收获1份俸禄",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22020,type: 30,name: "完成1次商会任务",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22021,type: 30,name: "完成2次行会任务",value: 2,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22022,type: 30,name: "进行1次神仙大会对战",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22023,type: 30,name: "挑战1次诛仙阵",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22024,type: 30,name: "完成1次商帮任务",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  
#1类 22110-22199
  - {id: 22110,type: 30,name: "到福地收获60元宝",value: 60,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22111,type: 30,name: "与野怪战斗8次",value: 8,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22112,type: 30,name: "钱庄领取8份税收",value: 8,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22113,type: 30,name: "炼丹房收取8份经验",value: 8,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22114,type: 30,name: "在地图上购买5张卡牌",value: 5,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22115,type: 30,name: "矿场收取15个元素",value: 15,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 22116,type: 30,name: "炼宝炉收取5个道具",value: 5,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
#2类 22210-22299
  - {id: 22210,type: 30,name: "使1个神仙附体（百宝箱不算）",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22211,type: 30,name: "到游商馆买入15件特产",value: 15,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22212,type: 30,name: "到秘宝阁购买5件法宝",value: 5,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
#3类 22310-22399
  - {id: 22310,type: 30,name: "到文王庙求签1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22311,type: 30,name: "到女娲庙捐赠1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22312,type: 30,name: "到迷仙洞探险1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22313,type: 30,name: "到鹿台升级卡牌1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22314,type: 30,name: "在路边捡到1个百宝箱",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 22315,type: 30,name: "到太一府捐献1次特产",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
#宝箱  此处宝箱奖励仅用于展示 ，实际领取的奖励配置在box目录下对应的yml中   {item: 120,num: 1} 为随机灵石*1
boxs: 
  - {id: 22901,boxKey: 706,score: 60,awards: [{item: 20,num: 5000},{item: 60,awardId: 11010,num: 1}],isValid: true}
  - {id: 22902,boxKey: 707,score: 100,awards: [{item: 20,num: 7500},{item: 30,num: 30}],isValid: true}
  - {id: 22903,boxKey: 708,score: 130,awards: [{item: 20,num: 10000},{item: 60,awardId: 11010,num: 1}],isValid: true}
  - {id: 22904,boxKey: 709,score: 160,awards: [{item: 20,num: 12500},{item: 30,num: 30}],isValid: true}
  - {id: 22905,boxKey: 710,score: 190,awards: [{item: 20,num: 15000},{item: 120,num: 1},{item: 60,awardId: 11010,num: 3}],isValid: true}
...