---
groupId: 23000
# 当isValid 设置有false时只允许获取奖励，不允许用来生成任务
tasks: 
#固定类 23010-23099
  - {id: 23010,type: 30,name: "今日首次登录游戏",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23011,type: 30,name: "消耗5个元素升级卡牌",value: 5,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23012,type: 30,name: "消耗60点体力",value: 60,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23013,type: 30,name: "领取1次封神台积分",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23014,type: 30,name: "使用1次地图法宝",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23015,type: 30,name: "使用1个战斗法宝",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23016,type: 30,name: "累计铜钱收益%s万",value: null,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23017,type: 30,name: "进行8次练兵",value: 8, awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23018,type: 30,name: "到商城花费元宝购物1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23019,type: 30,name: "收获1份俸禄",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23020,type: 30,name: "完成1次商会任务",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23021,type: 30,name: "完成2次行会任务",value: 2,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23022,type: 30,name: "进行1次神仙大会对战",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23023,type: 30,name: "挑战1次诛仙阵",value: 1,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23024,type: 30,name: "完成1次商帮任务",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
#1类 23010-23099
  - {id: 23110,type: 30,name: "到福地收获60元宝",value: 60,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23111,type: 30,name: "与野怪战斗8次",value: 8,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23112,type: 30,name: "钱庄领取15份税收",value: 15,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23113,type: 30,name: "炼丹房收取15份经验",value: 15,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23114,type: 30,name: "在地图上购买5张卡牌",value: 5,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23115,type: 30,name: "矿场收取40个元素",value: 40,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
  - {id: 23116,type: 30,name: "炼宝炉收取8个道具",value: 8,awards: [{item: 80,num: 200},{item: 100,num: 10}],isValid: true}
#2类 23010-23099
  - {id: 23210,type: 30,name: "使1个神仙附体（百宝箱不算）",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23211,type: 30,name: "到游商馆买入15件特产",value: 15,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23212,type: 30,name: "到秘宝阁购买5件法宝",value: 5,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
#3类 23010-23099
  - {id: 23310,type: 30,name: "到文王庙求签1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23311,type: 30,name: "到女娲庙捐赠1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23312,type: 30,name: "到迷仙洞探险1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23313,type: 30,name: "到鹿台升级卡牌1次",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23314,type: 30,name: "在路边捡到1个百宝箱",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
  - {id: 23315,type: 30,name: "到太一府捐献1次特产",value: 1,awards: [{item: 80,num: 400},{item: 100,num: 20}],isValid: true}
#宝箱  此处宝箱奖励仅用于展示 ，实际领取的奖励配置在box目录下对应的yml中   {item: 120,num: 1} 为随机灵石*1
boxs: 
  - {id: 23901,boxKey: 711,score: 60,awards: [{item: 20,num: 5000},{item: 60,awardId: 11010,num: 1}],isValid: true}
  - {id: 23902,boxKey: 712,score: 100,awards: [{item: 20,num: 7500},{item: 30,num: 30}],isValid: true}
  - {id: 23903,boxKey: 713,score: 130,awards: [{item: 20,num: 10000},{item: 60,awardId: 11010,num: 1}],isValid: true}
  - {id: 23904,boxKey: 714,score: 160,awards: [{item: 20,num: 12500},{item: 30,num: 30}],isValid: true}
  - {id: 23905,boxKey: 715,score: 190,awards: [{item: 20,num: 15000},{item: 120,num: 1},{item: 60,awardId: 11010,num: 3}],isValid: true}
...