---
groupId: 500
#每日任务列表：
# 当isValid 设置有false时只允许获取奖励，不允许用来生成任务
tasks: 
  - {id: 1100,type: 50,name: "累计攻下%d座城池",isValid: true}
  - {id: 1200,type: 50,name: "累计%d座城所有建筑满5级",isValid: true}
  - {id: 1300,type: 50,name: "累计收集%d张卡牌",isValid: true}
...