#客户端渠道编码,苹果官方渠道
channelId: 80000
#渠道产品ID与竹风产品ID映射。
channelMap:
  - {zfProductId: 11,innerId: bbw.fjfsz.300}
  - {zfProductId: 12,innerId: bbw.fjfsz.300}
  - {zfProductId: 13,innerId: bbw.fjfsz.60}
  - {zfProductId: 15,innerId: bbw.fjfsz.680}
  - {zfProductId: 16,innerId: bbw.fjfsz.980}
  - {zfProductId: 17,innerId: bbw.fjfsz.1980}
  - {zfProductId: 18,innerId: bbw.fjfsz.3280}
  - {zfProductId: 19,innerId: bbw.fjfsz.6480}
  - {zfProductId: 20,innerId: bbw.fjfsz.300}
  - {zfProductId: 21,innerId: bbw.fjfsz.680}
  - {zfProductId: 30,innerId: bbw.fjfsz.1980}
  #  - {zfProductId: 99001130,innerId: 每周灵石,price: 18,}
  - {zfProductId: 99001210,innerId: bbw.fjfsz.60}
  - {zfProductId: 99001211,innerId: bbw.fjfsz.10}
  - {zfProductId: 99001281,innerId: bbw.fjfsz.10}
  - {zfProductId: 99001282,innerId: bbw.fjfsz.60}
  #  - {zfProductId: 99001283,innerId: 法宝助力,price: 12}
  #  - {zfProductId: 99001000,innerId: 0元日礼包,price: 0}
  - {zfProductId: 99001006,innerId: bbw.fjfsz.60}
  - {zfProductId: 99001031,innerId: bbw.fjfsz.300}
  #  - {zfProductId: 99001100,innerId: 0元周礼包,price: 0}
  - {zfProductId: 99001170,innerId: bbw.fjfsz.680}
  - {zfProductId: 99001172,innerId: bbw.fjfsz.1980}
  - {zfProductId: 99001174,innerId: bbw.fjfsz.3280}
  #  - {zfProductId: 99001176,innerId: 448元周礼包,price: 448}
  #  - {zfProductId: 99001300,innerId: 0元月礼包,price: 0}
  - {zfProductId: 99001310,innerId: bbw.fjfsz.300}
  - {zfProductId: 99001315,innerId: bbw.fjfsz.680}
  - {zfProductId: 99001320,innerId: bbw.fjfsz.1980}
  - {zfProductId: 99001325,innerId: bbw.fjfsz.3280}
  #  - {zfProductId: 99001330,innerId: 448元月礼包,price: 448}
  - {zfProductId: 99001335,innerId: bbw.fjfsz.6480}
  #  - {zfProductId: 99001291,innerId: 破军星,price: 128}
  - {zfProductId: 99001292,innerId: bbw.fjfsz.6480}
  #特惠礼包
  - {zfProductId: 99001401,innerId: bbw.fjfsz.10}
  - {zfProductId: 99001402,innerId: bbw.fjfsz.3}
  - {zfProductId: 99001403,innerId: bbw.fjfsz.60}
  - {zfProductId: 99001404,innerId: bbw.fjfsz.600}
  #每日礼包
  - {zfProductId: 99001041,innerId: bbw.fjfsz.300}
  - {zfProductId: 99001042,innerId: bbw.fjfsz.680}
  - {zfProductId: 99001043,innerId: bbw.fjfsz.980}
  #每周礼包
  - {zfProductId: 99001102,innerId: bbw.fjfsz.980}
  - {zfProductId: 99001103,innerId: bbw.fjfsz.1980}
  - {zfProductId: 99001104,innerId: bbw.fjfsz.1980}
  - {zfProductId: 99001105,innerId: bbw.fjfsz.3280}
  - {zfProductId: 99001106,innerId: bbw.fjfsz.3280}
  #首冲
  - {zfProductId: 60,innerId: bbw.fjfsz.60}
  - {zfProductId: 61,innerId: bbw.fjfsz.300}
  - {zfProductId: 62,innerId: bbw.fjfsz.980}
  - {zfProductId: 63,innerId: bbw.fjfsz.1980}

  #梦魇首冲
  - {zfProductId: 70,innerId: bbw.fjfsz.60}
  - {zfProductId: 71,innerId: bbw.fjfsz.300}
  - {zfProductId: 72,innerId: bbw.fjfsz.980}
  - {zfProductId: 73,innerId: bbw.fjfsz.1980}
...