#CfgGodRoadEntity
#特殊建筑位置
--- {id: 117,name: 仙人洞}
--- {id: 125,name: 森林}
--- {id: 130,name: 野地}
--- {id: 217,name: 福地}
--- {id: 921,name: 客栈}
--- {id: 925,name: 福地}
--- {id: 1330,name: 福临轩}
--- {id: 1530,name: 村庄}
--- {id: 1617,name: 游商馆}
--- {id: 1624,name: 湖泊}
--- {id: 1630,name: 野地}
--- {id: 1717,name: 野地}
--- {id: 1908,name: 黑市}
--- {id: 1912,name: 野地}
--- {id: 1946,name: 福地}
--- {id: 2001,name: 客栈}
--- {id: 2008,name: 火山}
--- {id: 2014,name: 沙洲}
--- {id: 2609,name: 游商馆}
--- {id: 2612,name: 火山}
--- {id: 2630,name: 村庄}
--- {id: 2933,name: 福地}
--- {id: 2939,name: 福地}
--- {id: 3014,name: 矿山}
--- {id: 3046,name: 仙人洞}
--- {id: 3101,name: 森林}
--- {id: 3108,name: 野地}
--- {id: 3445,name: 福临轩}
--- {id: 3524,name: 黑市}
--- {id: 3616,name: 野地}
--- {id: 4017,name: 客栈}
--- {id: 4124,name: 游商馆}
--- {id: 4224,name: 福地}
--- {id: 4327,name: 野地}
--- {id: 4830,name: 村庄}
--- {id: 4930,name: 仙人洞}
--- {id: 5017,name: 野地}
--- {id: 5030,name: 客栈}