#卡牌技能
#参数说明：
# defensible: 是否可以防御（false则直接不走防御判定）
# totalTimes: 总可发动次数（在场时，上场技必须配置）,,roundTimes: 每回合可以发动的次数（上场技必须配置）,
# leaderCardSkillGroup: 在主角卡技海中的划分,ownSkills:附带的技能，如自带XXX

#CfgCardSkill
--- {id: 101,name: 飞行,defensible: false,leaderCardSkillGroup: 0}
--- {id: 102,name: 疾驰,defensible: false,leaderCardSkillGroup: 0}
--- {id: 103,name: 影随,defensible: false,leaderCardSkillGroup: 0}
#上场技能
--- {id: 1001,name: 斥退,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1002,name: 妖术,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1003,name: 主帅,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1004,name: 修仙,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1005,name: 混元,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1007,name: 瘟君,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1008,name: 升仙,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1009,name: 神疗,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1010,name: 超度,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1011,name: 绝杀,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1012,name: 暴起,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1013,name: 暗蛊,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1014,name: 让位,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1015,name: 混绫,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1016,name: 解封,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1017,name: 神医,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1018,name: 财神,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1,ownSkills: [1090,3001,3009]}
--- {id: 1019,name: 元帅,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1020,name: 暴刺,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1,ownSkills: [4201]}
--- {id: 1021,name: 幻化,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
#--- {id: 1022,name: 普渡,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1023,name: 蝗征,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}


--- {id: 1090,name: 招财,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1091,name: 主角卡经验,defensible: false,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}

--- {id: 1101,name: AI王者,defensible: false}
--- {id: 1102,name: 禁术,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1}
--- {id: 1103,name: 哮天,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1,ownSkills: [1005,1013,1102]}
--- {id: 1104,name: 祭鞭,defensible: true,totalTimes: 1,roundTimes: 1,leaderCardSkillGroup: 1,ownSkills: [3102]}
--- {id: 1105,name: 奉神,defensible: true,leaderCardSkillGroup: 2}
--- {id: 1106,name: 麒麟,defensible: true,leaderCardSkillGroup: 2}

--- {id: 1201,name: 复活,defensible: false,totalTimes: 5,roundTimes: 5,leaderCardSkillGroup: 5}
--- {id: 1202,name: 死士,defensible: true,leaderCardSkillGroup: 5}
--- {id: 1203,name: 死咒,defensible: true,leaderCardSkillGroup: 5}
--- {id: 1204,name: 怨灵,defensible: true,leaderCardSkillGroup: 5}
--- {id: 1205,name: 长生,defensible: false,leaderCardSkillGroup: 5}
--- {id: 1206,name: 咒怨,defensible: true,leaderCardSkillGroup: 5}
--- {id: 1207,name: 鬼雄,defensible: false,leaderCardSkillGroup: 5}
--- {id: 1208,name: 殇咒,defensible: false,leaderCardSkillGroup: 5}
--- {id: 1209,name: 朱雀,defensible: false,leaderCardSkillGroup: 5,ownSkills: [101,1201]}
#组合技
--- {id: 2001,name: 十绝阵,defensible: true}
--- {id: 2002,name: 黄家军,defensible: false}
--- {id: 2003,name: 陈塘家,defensible: false}
--- {id: 2004,name: 九曲黄河阵,defensible: false}
--- {id: 2005,name: 迷魂阵,defensible: true}
--- {id: 2006,name: 四大天王,defensible: false}
--- {id: 2007,name: 哼哈二将,defensible: false}
--- {id: 2008,name: 千里眼顺风耳,defensible: false}
--- {id: 2009,name: 九龙岛四圣,defensible: false}
--- {id: 2010,name: 梅山七怪,defensible: false}
--- {id: 2011,name: 左右门神,defensible: false}
--- {id: 2012,name: 四海龙王,defensible: true}
--- {id: 2013,name: 晁式兄弟,defensible: false}
--- {id: 2014,name: 殷洪四天君,defensible: false}
--- {id: 2015,name: 神力横扫,defensible: false}
--- {id: 2016,name: 闻仲四天君,defensible: false}
--- {id: 2017,name: 古兽来袭,defensible: false}
--- {id: 2018,name: 行瘟使者,defensible: false}
--- {id: 2019,name: 四圣显灵,defensible: false}
--- {id: 2020,name: 上古神力,defensible: false}

--- {id: 2201,name: 联攻,defensible: false,leaderCardSkillGroup: 0}
--- {id: 3001,name: 金刚,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3002,name: 刚毅,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3003,name: 心止,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3004,name: 自在,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3005,name: 避雷,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3006,name: 定风,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3007,name: 真金,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3008,name: 返照,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3009,name: 祛毒,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3010,name: 法盾,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3011,name: 灵守,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3012,name: 乾坤,defensible: false,leaderCardSkillGroup: 4,ownSkills: [1201]}
--- {id: 3013,name: 法身,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3014,name: 连环,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3015,name: 金身,defensible: false,leaderCardSkillGroup: 4,ownSkills: [3001]}
--- {id: 3016,name: 神照,defensible: true,leaderCardSkillGroup: 4}
--- {id: 3017,name: 金罩,defensible: false,leaderCardSkillGroup: 4,ownSkills: [3001,3016]}
--- {id: 3018,name: 璧环,defensible: false,leaderCardSkillGroup: 4}
--- {id: 3019,name: 玄武,defensible: false,leaderCardSkillGroup: 4,ownSkills: [3011,3140]}


--- {id: 3501,name: 伏虎,defensible: true,leaderCardSkillGroup: 2,ownSkills: [3502]}
--- {id: 3502,name: 隐藏伏虎,defensible: false,leaderCardSkillGroup: 0}

--- {id: 3101,name: 飞狙,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3102,name: 拦截,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3103,name: 治愈,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3104,name: 封神,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3105,name: 回魂,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3106,name: 魅惑,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3107,name: 威风,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3108,name: 闪电,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3109,name: 业火,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3110,name: 噬魂,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3111,name: 王者,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3112,name: 枷锁,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3113,name: 得道,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3114,name: 生金,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3115,name: 生木,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3116,name: 生水,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3117,name: 生火,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3118,name: 生土,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3119,name: 强金,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3120,name: 强木,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3121,name: 强水,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3122,name: 强火,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3123,name: 强土,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3124,name: 流毒,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3125,name: 圣火,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3126,name: 道法,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3127,name: 入痘,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3128,name: 灭魄,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3130,name: 自愈,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3131,name: 封咒,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3132,name: 蛊惑,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3133,name: 吸星,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3134,name: 双狙,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3135,name: 震慑,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3136,name: 鼓舞,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3137,name: 雷电,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3138,name: 连锁,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3139,name: 火球,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3140,name: 力盾,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3141,name: 巫医,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3142,name: 幻术,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3143,name: 解封,defensible: false,leaderCardSkillGroup: 2,ownSkills: [1016]}
--- {id: 3144,name: 挑拨,defensible: true,leaderCardSkillGroup: 2}

--- {id: 3145,name: 落羽,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3146,name: 反间,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3147,name: 蚀月,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3148,name: 冷刀,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3149,name: 化血,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3150,name: 悲愤,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3151,name: 袍泽,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3152,name: 食尸,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3153,name: 镜像,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3154,name: 偷营,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3155,name: 弘法,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3156,name: 激励,defensible: false,leaderCardSkillGroup: 2}
--- {id: 3157,name: 神光,defensible: true,leaderCardSkillGroup: 2,ownSkills: [3008]}
--- {id: 3158,name: 烈焰,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3159,name: 炙焰,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3160,name: 分身,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3161,name: 度升,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3162,name: 吸阳,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3163,name: 倾国,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3164,name: 玄幻,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3165,name: 蜂袋,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3166,name: 解毒,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3167,name: 毒矢,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3168,name: 毒镖,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3170,name: 疾军,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3171,name: 痘仙,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3172,name: 天雷,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3173,name: 白虎,defensible: true,leaderCardSkillGroup: 2,ownSkills: [3009,3143,1016]}
--- {id: 3175,name: 隐藏蝗征,defensible: true,leaderCardSkillGroup: 2}
--- {id: 3176,name: 痊愈,defensible: true,leaderCardSkillGroup: 2}

--- {id: 3201,name: 回光,defensible: true,leaderCardSkillGroup: 4}
--- {id: 3202,name: 反射,defensible: true,leaderCardSkillGroup: 4}
--- {id: 3301,name: 坚毅,defensible: false,leaderCardSkillGroup: 4,ownSkills: [4601]}
--- {id: 3302,name: 怒意,defensible: false,leaderCardSkillGroup: 4,ownSkills: [4602]}

--- {id: 3901,name: 火枪,defensible: true,leaderCardSkillGroup: 3,ownSkills: [4301,4201]}
--- {id: 3902,name: 狙杀,defensible: true,leaderCardSkillGroup: 3}

--- {id: 4001,name: 无相,defensible: false,leaderCardSkillGroup: 4}
--- {id: 4401,name: 普通攻击,defensible: true}
--- {id: 4104,name: 暴击,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4106,name: 金克木,defensible: true}
--- {id: 4107,name: 木克土,defensible: true}
--- {id: 4108,name: 土克水,defensible: true}
--- {id: 4109,name: 水克火,defensible: true}
--- {id: 4110,name: 火克金,defensible: true}
--- {id: 4111,name: 龙息,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4112,name: 突袭,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4113,name: 死斗,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4114,name: 神剑,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4115,name: 销魂,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4116,name: 太极,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4117,name: 克敌,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4119,name: 诛仙,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4120,name: 突击,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4121,name: 青龙,defensible: true,leaderCardSkillGroup: 3,ownSkills: [101,4104]}

--- {id: 4201,name: 穿刺,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4202,name: 吸血,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4203,name: 嗜血,defensible: true,leaderCardSkillGroup: 3}

--- {id: 4451,name: 连击,defensible: true,leaderCardSkillGroup: 3}

--- {id: 4301,name: 奇袭,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4302,name: 钻地,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4303,name: 地劫,defensible: true,leaderCardSkillGroup: 3}
--- {id: 4304,name: 潜龙,defensible: true,leaderCardSkillGroup: 3,ownSkills: [4303,4111]}

--- {id: 4501,name: 灵动,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4502,name: 芒刺,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4503,name: 飞闪,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4504,name: 战刺,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4505,name: 嘲讽,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4601,name: 隐藏坚毅,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4602,name: 隐藏怒意,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4603,name: 逃遁,defensible: true,leaderCardSkillGroup: 4}
--- {id: 4599,name: 普通防御,defensible: false}
--- {id: 5001,name: 护卫,defensible: false,leaderCardSkillGroup: 4}
--- {id: 5002,name: 宝鉴,defensible: false,leaderCardSkillGroup: 4}
--- {id: 6002,name: 兴法,defensible: false,leaderCardSkillGroup: 0}
--- {id: 6003,name: 诛仙,defensible: false,leaderCardSkillGroup: 0}
--- {id: 6004,name: 绝仙,defensible: true,leaderCardSkillGroup: 0}
--- {id: 6005,name: 诛绝,defensible: true,leaderCardSkillGroup: 0,ownSkills: [4119,6004]}


#法器技能
#技能组1
--- {id: 10101,name: 斩魄,defensible: true,leaderCardSkillGroup: 0}
--- {id: 10102,name: 破天,defensible: true,leaderCardSkillGroup: 0}
#技能组2
--- {id: 10201,name: 追风,defensible: true,leaderCardSkillGroup: 0}
--- {id: 10202,name: 蚀骨,defensible: true,leaderCardSkillGroup: 0}

#法宝技能
#技能组1
--- {id: 11101,name: 鼋甲,defensible: true,leaderCardSkillGroup: 0}
--- {id: 11102,name: 龙麟,defensible: true,leaderCardSkillGroup: 0}
#技能组2
--- {id: 11201,name: 绝影,defensible: true,leaderCardSkillGroup: 0}
--- {id: 11202,name: 刺胄,defensible: true,leaderCardSkillGroup: 0}