#战斗法宝
#CfgWeapon
--- {id: 210,name: 番天印} #直接选定敌方一张卡牌送入坟场，无视其金刚效果。
--- {id: 220,name: 打神鞭} #封杀敌方所有卡牌所有特技一回合。
--- {id: 230,name: 阴阳镜} #拉己方一张坟场中的卡牌回战场。
--- {id: 240,name: 太极图} #控制敌方一张卡牌一回合。
--- {id: 250,name: 诛仙剑} #装备卡牌攻防+500。
--- {id: 260,name: 九龙神火罩} #封杀敌方一张卡牌，使其不能攻击也不能阻挡。
--- {id: 270,name: 莫邪宝剑} #装备卡牌攻防+380。
--- {id: 280,name: 招魂幡} # 每回合召唤一鬼兵进场。
--- {id: 290,name: 戮仙剑} # 装备卡牌攻击+500且获得特技嗜血。
--- {id: 300,name: 攒心钉} #每回合针对敌方防御最低的卡牌，破除其250点永久防御。一场战斗限用1次。
--- {id: 310,name: 乾坤尺} #装备卡牌攻击+400且获得特技钻地。
--- {id: 320,name: 紫金钵盂} #使用回合己方所有卡牌均可上云台。
--- {id: 330,name: 紫绫仙衣} #己方所有卡牌防守+100。
--- {id: 340,name: 绝仙剑} # 装备卡牌攻防各+250且获得特技穿刺。
--- {id: 350,name: 乾坤弓} # 给敌方血槽造成450~800点伤害，一次战斗限三次。
--- {id: 360,name: 震天箭} #给敌方血槽造成500点伤害，一次战斗限三次。
--- {id: 370,name: 红葫芦} #补己方召唤师600点血，一次战斗限五次。
--- {id: 380,name: 金葫芦} # 使用回合己方所有卡牌不会陷入异常状态。
--- {id: 390,name: 陷仙剑} #装备卡牌攻防各+200。
--- {id: 400,name: 混元金斗} #当前回合营地所有卡牌召唤成本-1，一场战斗限使用3次。
--- {id: 410,name: 青云剑} # 装备卡牌攻防各+100。
--- {id: 420,name: 定神丹} #使用回合己方所有卡牌不会受威风、斥退、妖术的影响。
--- {id: 430,name: 扫霞衣} #装备卡牌防守+500。
--- {id: 440,name: 五火神焰扇} #给对方全体卡牌150~500点业火伤害（无视金刚和云台位）。
--- {id: 450,name: 柴胡草} #治疗一张卡牌受到的所有永久性伤害。一场战斗限用1次。
--- {id: 460,name: 如意乾坤袋} #可将当前营地中的卡牌全部换掉。
--- {id: 470,name: 太极符印} # 装备后卡牌在战斗中获得无相技能。
--- {id: 480,name: 火龙标} # 给予对方一张卡牌150点血的永久伤害。一次战斗限使用3次。
--- {id: 490,name: 百毒痘} #使对方一张卡牌中毒，每回合造成100点血的永久伤害。