# com.bbw.god.game.combat.runes
#CfgRunes 符文信息
--- {id: 131620,name: 雷纹符,runeType: 0}
--- {id: 131630,name: 毒纹符,runeType: 0}
--- {id: 131640,name: 火纹符,runeType: 0}
--- {id: 131650,name: 刃纹符,runeType: 0}
--- {id: 131690,name: 净火符,runeType: 0}

--- {id: 131240,name: 勇武符,runeType: 1}
--- {id: 131070,name: 疾驰符,runeType: 1}
--- {id: 131250,name: 龙息符,runeType: 1}
--- {id: 131370,name: 回光符,runeType: 1}
--- {id: 131110,name: 无相符,runeType: 1}
--- {id: 131060,name: 飞天符,runeType: 1}
--- {id: 131390,name: 同袍符,runeType: 1}
--- {id: 131410,name: 销魂符,runeType: 1}
--- {id: 131440,name: 死士符,runeType: 1}
--- {id: 131450,name: 芒刺符,runeType: 1}
--- {id: 131460,name: 钻地符,runeType: 1}
--- {id: 131080,name: 神剑符,runeType: 1}
--- {id: 131020,name: 定风符,runeType: 1}
--- {id: 131140,name: 穿刺符,runeType: 1}
--- {id: 131090,name: 自愈符,runeType: 1}
--- {id: 131050,name: 舞戚符,runeType: 1}
--- {id: 131170,name: 毒沼符,runeType: 1}
--- {id: 131210,name: 威慑符,runeType: 1}
--- {id: 131220,name: 道法符,runeType: 1}
--- {id: 131260,name: 群嘲符,runeType: 1}
--- {id: 131280,name: 同泽符,runeType: 1}
--- {id: 131320,name: 大疫符,runeType: 1}
--- {id: 131340,name: 圣元符,runeType: 1}
--- {id: 131420,name: 封神符,runeType: 1}
--- {id: 131500,name: 鼓舞符,runeType: 1}
--- {id: 131510,name: 震慑符,runeType: 1}
--- {id: 131550,name: 辟地符,runeType: 1}
--- {id: 131570,name: 迟缓符,runeType: 1}
--- {id: 131270,name: 自毙符,runeType: 1}
--- {id: 131290,name: 陷仙符,runeType: 1}
--- {id: 131300,name: 戮仙符,runeType: 1}
--- {id: 131310,name: 天斩符,runeType: 1}
--- {id: 131350,name: 刚烈符,runeType: 1}
--- {id: 131400,name: 巫术符,runeType: 1}
--- {id: 131470,name: 亡命符,runeType: 1}
--- {id: 131540,name: 宝鉴符,runeType: 1}
--- {id: 131330,name: 永生符,runeType: 1}
--- {id: 131360,name: 天赋符,runeType: 1}
--- {id: 131010,name: 泰体符,runeType: 1}
--- {id: 131120,name: 飞仙符,runeType: 1}
--- {id: 131040,name: 招魂符,runeType: 1}
--- {id: 131190,name: 克火符,runeType: 1}
--- {id: 131490,name: 得道符,runeType: 1}
--- {id: 131520,name: 健体符,runeType: 1}
--- {id: 131530,name: 升仙符,runeType: 1}
--- {id: 131160,name: 灭魄符,runeType: 1}
--- {id: 131380,name: 避雷符,runeType: 1}
--- {id: 131150,name: 蛊惑符,runeType: 1}
--- {id: 131200,name: 挑离符,runeType: 1}
--- {id: 131180,name: 封天符,runeType: 1}
--- {id: 131100,name: 禁法符,runeType: 1}
--- {id: 131560,name: 缓速符,runeType: 1}
--- {id: 131610,name: 哼哈符,runeType: 1}
--- {id: 131660,name: 激将符,runeType: 1}
--- {id: 131670,name: 军师符,runeType: 1}
--- {id: 131680,name: 不动符,runeType: 1}
--- {id: 131130,name: 圣火符,runeType: 1}

--- {id: 131230,name: 鬼画符,runeType: 2}
--- {id: 131030,name: 天残符,runeType: 2}
--- {id: 131480,name: 落石符,runeType: 2}

--- {id: 131580,name: 天魔符,runeType: 3}
--- {id: 131590,name: 地魔符,runeType: 3}
--- {id: 131600,name: 人魔符,runeType: 3}