# 梦魇世界  野怪符文配置
---

#普通野怪的符文
normalRunes: ["毒沼符", "疾驰符", "灭魄符", "道法符", "回光符", "自愈符", "泰体符", "飞仙符", "招魂符", "无相符", "飞天符", "避雷符", "同袍符", "巫术符", "销魂符", "封神符", "芒刺符", "落石符", "封天符", "禁法符", "神剑符", "定风符", "克火符", "蛊惑符", "挑离符", "穿刺符", "得道符", "鼓舞符", "震慑符", "健体符", "升仙符", "宝鉴符", "辟地符", "缓速符", "迟缓符"]

#精英野怪的符文
eliteRunes: ["圣火符","舞戚符","威慑符","鬼画符","联攻符","龙息符","群嘲符","自毙符","陷仙符","戮仙符","天斩符","大疫符","永生符","圣元符","刚烈符","天赋符","死士符","钻地符","天残符"]

...