key: 11790
desc: 随机获得以下奖励之一：铜钱*20万、元宝*20、魂源*1、通天残卷*1
isRandom: true
categoryNum: 1
goods: 
  -
    item: 20
    num: 200000
    prop: 3500
  -
    item: 10
    num: 20
    prop: 3000
  -
    item: 60
    good: 魂源
    num: 1
    prop: 1800
  -
    item: 60
    good: 通天残卷
    num: 1
    prop: 1700
...