#箱子标识
key: 530
#箱子描述
desc: 随机元宝
#是否随机
isRandom: true
#可获得多少种物品
categoryNum: 1
#物品
goods: 
  -
    item: 10 # 元宝
    num: 68
    prop: 2500
  -
    item: 10 # 元宝
    num: 88
    prop: 3600
  -
    item: 10 # 元宝
    num: 128
    prop: 3500
  -
    item: 10 # 元宝
    num: 288
    prop: 200
  -
    item: 10 # 元宝
    num: 388
    prop: 100
  -
    item: 10 # 元宝
    num: 588
    prop: 60
  -
    item: 10 # 元宝
    num: 688
    prop: 40
...