key: 11810
desc: 随机获得以下奖励之一：铜钱*120万、元宝*120、魂源*6、通天残卷*6
isRandom: true
categoryNum: 1
goods: 
  -
    item: 20
    num: 1200000
    prop: 3500
  -
    item: 10
    num: 120
    prop: 3000
  -
    item: 60
    good: 魂源
    num: 6
    prop: 1800
  -
    item: 60
    good: 通天残卷
    num: 6
    prop: 1700
...