#史诗级每日女娲礼包
#箱子标识，对应
key: 50236
#箱子描述
desc: 必得荣耀铜币*300,有100%概率获得神格牌、神将羁绊法宝或技能衍生残页等。
#是否随机
isRandom: false
#可获得多少种物品
categoryNum: 1
#物品
goods:
  - item: 60 # 道具
    good: 荣耀铜币
    num: 300
    prop: 10000

...