#噩梦BOSS宝箱
#箱子标识，对应
key: 50416
#箱子描述
desc: 可获得：随机本源*5、金雷竹*5、养魂木*5、破阵玉牌*35。
#是否随机
isRandom: false
#物品
goods:
  -
    item: 60 # 道具
    good: 随机本源
    num: 5
  -
    item: 60 # 道具
    good: 金雷竹
    num: 5
  -
    item: 60 # 道具
    good: 养魂木
    num: 5
  -
    item: 60 # 道具
    good: 破阵玉牌
    num: 35
...