#困难BOSS宝箱
#箱子标识，对应
key: 50414
#箱子描述
desc: 可获得：随机本源*4、金雷竹*4、养魂木*4、破阵玉牌*30。
#是否随机
isRandom: false
#物品
goods:
  -
    item: 60 # 道具
    good: 随机本源
    num: 4
  -
    item: 60 # 道具
    good: 金雷竹
    num: 4
  -
    item: 60 # 道具
    good: 养魂木
    num: 4
  -
    item: 60 # 道具
    good: 破阵玉牌
    num: 30
...