#地狱BOSS宝箱
#箱子标识，对应
key: 50418
#箱子描述
desc: 可获得：随机本源*6、金雷竹*6、养魂木*6、破阵玉牌*50。
#是否随机
isRandom: false
#物品
goods:
  -
    item: 60 # 道具
    good: 随机本源
    num: 6
  -
    item: 60 # 道具
    good: 金雷竹
    num: 6
  -
    item: 60 # 道具
    good: 养魂木
    num: 6
  -
    item: 60 # 道具
    good: 破阵玉牌
    num: 50
...
