#箱子标识
key: 50200
#箱子描述
desc: 小型鞭炮礼包
isRandom: true
categoryNum: 1
#物品
goods:
  - item: 60
    good: 窜天猴
    num: 1
    prop: 7900
  - item: 60
    good: 二踢脚
    num: 1
    prop: 2000
  - item: 60
    good: 大地红
    num: 1
    prop: 100
...