#战令四星神将礼包
#箱子标识，对应
key: 11680
#箱子描述
desc: 随机1个物品
#是否随机
isRandom: true
#可获得多少种物品
categoryNum: 1
#物品
goods:
  - item: 40 # 卡牌
    good: 栢鉴
    num: 1
    prop: 1
  - item: 40 # 卡牌
    good: 女娲灵守
    num: 1
    prop: 3
  - item: 40 # 卡牌
    good: 马元
    num: 1
    prop: 1
  - item: 40 # 卡牌
    good: 度厄真人
    num: 1
    prop: 3
  - item: 40 # 卡牌
    good: 夔牛
    num: 1
    prop: 2
  - item: 40 # 卡牌
    good: 板角青牛
    num: 1
    prop: 1
  - item: 40 # 卡牌
    good: 玄坛黑虎
    num: 1
    prop: 1
  - item: 60 # 道具
    good: 仙之源
    num: 1
    prop: 488
  - item: 60 # 道具
    good: 魂源
    num: 2
    prop: 500
  - item: 60 # 道具
    good: 魂源
    num: 1
    prop: 1500
  - item: 60 # 道具
    good: 通天残卷
    num: 2
    prop: 1500
  - item: 20 # 铜钱
    num: 500000
    prop: 1500
  - item: 60 # 道具
    good: 夺宝积分
    num: 20
    prop: 1500
  - item: 60 # 道具
    good: 战令经验
    num: 200
    prop: 1500
  - item: 60 # 道具
    good: 战令经验
    num: 100
    prop: 1500
...