#战斗助力礼包
#箱子标识，对应
key: 50156
#箱子描述
desc: 可获得：番天印*1、九龙神火罩*1、打神鞭*1、阴阳镜*1、如意乾坤袋*1。
#是否随机
isRandom: false
#物品
goods: 
  -
    item: 60 # 道具
    good: 番天印
    num: 1
  -
    item: 60 # 道具
    good: 九龙神火罩
    num: 1
  -
    item: 60 # 道具
    good: 打神鞭
    num: 1
  -
    item: 60 # 道具
    good: 阴阳镜
    num: 1
  -
    item: 60 # 道具
    good: 如意乾坤袋
    num: 1
...
