#箱子标识
key: "普通野怪宝箱_升级_玩家等级[20,29]"
#箱子描述
desc: 随机1种物品
#是否随机
isRandom: true
#可获得多少种物品
categoryNum: 1
#物品
goods:
  - item: 40 #卡牌
    good: "普通野怪卡牌_升级_玩家等级[20,29]"
    num: 1
    prop: 3000
  - item: 60 #道具
    good: 法宝
    num: 1
    prop: 400
    starProps:
      - 2350
      - 2350
      - 3700
      - 1100
      - 500
  - item: 60 #道具
    good: 万能灵石
    num: 1
    prop: 400
    starProps:
      - 0
      - 3300
      - 4700
      - 1600
      - 400
  - item: 30 #体力
    good: 体力
    num: 30
    prop: 800
  - item: 50 #元素
    good: 随机
    num: 10
    prop: 800
  - item: 20 #铜钱
    good: 铜钱
    num: 6000
    prop: 920
  - item: 20 #铜钱
    good: 铜钱
    num: 8000
    prop: 1380
  - item: 20 #铜钱
    good: 铜钱
    num: 10000
    prop: 1380
  - item: 20 #铜钱
    good: 铜钱
    num: 15000
    prop: 460
  - item: 20 #铜钱
    good: 铜钱
    num: 20000
    prop: 322
  - item: 20 #铜钱
    good: 铜钱
    num: 30000
    prop: 138
...