#普通BOSS宝箱
#箱子标识，对应
key: 50412
#箱子描述
desc: 可获得：随机本源*3、金雷竹*3、养魂木*3、破阵玉牌*13。
#是否随机
isRandom: false
#物品
goods:
  -
    item: 60 # 道具
    good: 随机本源
    num: 3
  -
    item: 60 # 道具
    good: 金雷竹
    num: 3
  -
    item: 60 # 道具
    good: 养魂木
    num: 3
  -
    item: 60 # 道具
    good: 破阵玉牌
    num: 13
...