#箱子标识
key: 715
#箱子描述
desc: 3个物品
#是否随机
isRandom: false
#可获得多少种物品
categoryNum: 3
#物品
goods: 
  -
    item: 20 # 铜钱
    num: 15000
    prop: 10000
  -
    item: 60 #道具
    good: 万能灵石
    num: 1
    prop: 10000
    starProps: #万能灵石星级概率
      - 3200
      - 3200
      - 3300
      - 200
      - 100
  -
    item: 60 #通天残页
    good: 通天残卷
    num: 3
    prop: 10000
...