#箱子标识
key: 718
#箱子描述
desc: 随机1个物品
#是否随机
isRandom: false
#可获得多少种物品
categoryNum: 2
#物品
goods: 
  -
    item: 20 # 铜钱
    num: 7500
    prop: 3600
  -
    item: 50 #元素
    good: 随机
    num: 8
    prop: 3300
...