#箱子标识
key: 708
#箱子描述
desc: 随机2个物品
#是否随机
isRandom: false
#可获得多少种物品
categoryNum: 2
#物品
goods: 
  -
    item: 20 # 铜钱
    num: 10000
    prop: 3600
  -
    item: 60 #通天残页
    good: 通天残卷
    num: 1
    prop: 10000
...