#箱子标识
key: 520
#箱子描述
desc: 铜钱、体力、万能灵石、法宝、元素
#是否随机
isRandom: false
#物品
goods: 
  -
    item: 20 # 铜钱
    num: 30000
  -
    item: 30 #体力
    num: 30
  -
    item: 60 #道具
    good: 万能灵石
    num: 1
    starProps: #万能灵石星级概率
      - 3200
      - 3200
      - 3300
      - 200
      - 100
  -
    item: 60 #道具
    good: 法宝
    num: 1
    starProps: # 法宝星级概率
      - 2500
      - 2500
      - 3800
      - 800
      - 400
  -
    item: 50 #元素
    good: 随机
    num: 2
...