#简单精英宝箱
#箱子标识，对应
key: 50409
#箱子描述
desc: 可获得：随机本源*1、金雷竹*1、养魂木*1、破阵玉牌*3。
#是否随机
isRandom: false
#物品
goods:
  -
    item: 60 # 道具
    good: 随机本源
    num: 1
  -
    item: 60 # 道具
    good: 金雷竹
    num: 1
  -
    item: 60 # 道具
    good: 养魂木
    num: 1
  -
    item: 60 # 道具
    good: 破阵玉牌
    num: 3
...
