#随机奖励
#箱子标识，对应
key: 50326
#箱子描述
desc: 随机1个物品
#是否随机
isRandom: true
#可获得多少种物品
categoryNum: 1
#物品
goods:
  - item: 60 # 道具
    good: 通天残卷
    num: 2
    prop: 500
  - item: 20 # 铜钱
    num: 10000
    prop: 5000
  - item: 60 # 道具
    good: 随机元素
    num: 1
    prop: 4500

...